### ISSUE TITLE
A way to NOT requre android.permission.WRITE_EXTERNAL_STORAGE?

### ISSUE THREAD

**Issue by kirillgroshkov** [apache/cordova-plugin-file#243]
Is there a way to NOT require `android.permission.WRITE_EXTERNAL_STORAGE`? Our users complain that they see that the app requires access to "Photos/Media/Files", but we don't need access to Photos and Media.

> Starting in API level 19, this permission is not required to read/write files in your application-specific directories returned by Context.getExternalFilesDir(String) and Context.getExternalCacheDir().

https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE

> Internal file storage: Store app-private files on the device file system.
> External file storage: Store files on the shared external file system. This is usually for shared user files, such as photos.

https://developer.android.com/guide/topics/data/data-storage

**Comment by davidhooey** [comment]
Having the same problem. App does not require EXTERNAL storage, but the permission is still requested. User's are confused as to why they are being asked to grant access to Photos and Media.

**Comment by davidhooey** [comment]
In my case, downgrading to version `3.0.0` avoids the permission request.

**Comment by breautek** [comment]
At this time, there is no way, short of manipulating the `AndroidManifest.xml` before build, which you may be able to do via a hook.

I removed the support label, because I definitely see the use case here. Could be a feature request to opt in/out of adding the permission tag. The feature would have to be opt out to avoid introducing a breaking change.

**Comment by russaa** [comment]
a workaround I am currently using:  

create a minimal cordova plugin which basically only consists of the `plugin.xml` where the `` permission is removed, something like
```xml
<?xml version='1.0' encoding='utf-8'?>
<plugin id="cordova-plugin-remove-android-write-external-storage-permission" version="0.0.1" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
<name>RemoveWriteExternalStoragePermission</name>

<platform name="android">

  <!-- HACK must use file="app/src/main/AndroidManifest.xml" otherwise cordova thinks this is a confict (... but with adding permissions via config-files directives ... probably a BUG in cordova-common) -->
  <edit-config file="app/src/main/AndroidManifest.xml" target="/manifest" mode="merge">
    <manifest xmlns:tools="http://schemas.android.com/tools" />
  </edit-config>

  <config-file target="AndroidManifest.xml" parent="/*">
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
  </config-file>

</platform>

</plugin>
```
