### ISSUE TITLE
How to save binary data of zip file in cordova?

### ISSUE THREAD

**Issue by sreeraj137** [apache/cordova-plugin-file#245]
I am getting below response from axios.
this is response of zip file. please let me know how to save this filename.zip in cordova. Inside the ZIP there is image files.

PKM	14528.jpgìºwXSÛ¶7DD4)RE:¡7!ÙÒ{ÄH	-t¢R¥*
(UDjDzt¥*U@	"Ò/î³÷¹÷çsÏ{ßçûëÝ3ÏÊ+sÌ9Æå7ÖZÔOÔEÀic#àÝ1;® `î©)@0ÒÐÓzt´Àð{¸E'ð÷¾Ô4Çh_J¿¾Â´#Nù÷>íHÿAÿð{û5ã¯ë¿õnÃo¹\÷Ã<áþ"úú"R¦®Pß¯ki@YQIS[QI[IIDYI[MQ[U	8þðøßgøüî?VúüØ³1è=§ÿ³OçükÞÿÇvÂ38Ø_ôRpýµ(Üpõ*)(:`¿+ÔÛ-

**Comment by janpio** [comment]
What is axios?

**Comment by sreeraj137** [comment]
https://github.com/axios/axios

**Comment by janpio** [comment]
How is this relevant to `cordova-plugin-file` then?

**Comment by sreeraj137** [comment]
how we could write the zip file in .dataDirectory using cordova-plugin-file. Below is the sample code used.
var blob = new Blob([response.data], {type: 'application/zip'});
 fileWriter.write(blob);

**Comment by janpio** [comment]
The documentation has something on storing existing binary files:
https://github.com/apache/cordova-plugin-file#store-an-existing-binary-file-
Did you try this?
