### ISSUE TITLE
Export typings

### ISSUE THREAD

**Issue by BorntraegerMarc** [apache/cordova-plugin-file#247]
At the moment none of the types in the `index.d.ts` are exported. Thus nobody can use them. They should be `exported`

**Comment by janpio** [comment]
Feel free to create a Pull Request to fix this. We would really appreciate it.

**Comment by BorntraegerMarc** [comment]
Hey @janpio 
I didn't provide a PR because it seems that nobody will merge it anyway based on the open PR's of this repository :/

**Comment by jcesarmobile** [comment]
The export is not really needed, you can use the plugin using triple slash directive like this

`/// <reference types="cordova-plugin-file" />`

**Comment by BorntraegerMarc** [comment]
@jcesarmobile I think that is not a viable solution since (as far as I know) developers _using_ a typescript definition shouldn't need to add a reference in their TS files. They should be able to import them normally.

The `reference` is specifically for publishing dependencies in a own `@types/` library.

At least this is the best practice I've come around...

**Comment by jcesarmobile** [comment]
I’m not a typescript expert, but you said nobody can use the types bescause they are not exported. I told you a way you can use them. As I said, I’m no expert and I don’t know if it’s a good practice or not, but it’s a viable solution.

If you don’t like to use the triple slash directive, as janpio said, you can send a PR with the exports.

**Comment by BorntraegerMarc** [comment]
@jcesarmobile added PR https://github.com/apache/cordova-plugin-file/pull/285

**Comment by timbru31** [comment]
Thanks for your PR, but IHMO this is not needed. The `types` property is defined in the `package.json` and pointing to the correct `d.ts` file. You should only need to specify this plugin under your types array, see: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

Could you elaborate why these typings are otherwise not usable or share your `tsconfig.json` file?
