### ISSUE TITLE
Not found file using method documentsDirectory 

### ISSUE THREAD

**Issue by joaoduartemariucio** [apache/cordova-plugin-file#249]
I am using the plugin-plugin-file to save some image downloads without device, but there is a problem to recover images as saved. I'm sure the images are being saved but I can not see how in the iOS photo gallery how to keys this problem?

**Comment by lokesh75way** [comment]
I am facing the same issue,
is any one help me regarding this.

**Comment by breautek** [comment]
Sorry that this hasn't receive any attention. I'll be closing this due staleness. If a problem still exists on current versions, please do open a new issue with the issue form filled out.
