### ISSUE TITLE
in ios doesn't read file even if it is exist

### ISSUE THREAD

**Issue by NaleenDissanayake** [apache/cordova-plugin-file#250]
Android and Web is okay but when run ios it doesn't load the images.

**Comment by premtemp1** [comment]
Hello,
  It seems like you are able to see file on Android... I an not able to see file in any directory... Can you share how you are able to get file to show up.. Did you use a permission plugin

**Comment by janpio** [comment]
@premtemp1 This is not a discussion forum. Please keep discussion of _your_ problems to _your_ issues. Alternatively, post your problem on StackOverflow or ask on Slack (slack.cordova.io).

**Comment by janpio** [comment]
Did you solve the problem @NaleenDissanayake?

**Comment by NaleenDissanayake** [comment]
Yes.
