### ISSUE TITLE
Cordova plugin file does not work

### ISSUE THREAD

**Issue by anivaisu** [apache/cordova-plugin-file#254]
Hi,

I am using ionic 3.

Installed cordova plugin file version 4.3.3
cordova version is 8.0.0

all directories are null.

How can i fix this issues,

Kindly advice me,

Thanks.

**Comment by jessemonroy650** [comment]
I am having the same problem using Phonegap Build (the online build tool).

**Comment by premtemp1** [comment]
I am having same issue. These are folders that I am traversing
 var localURLs = [
                cordova.file.applicationDirectory,
                cordova.file.applicationStorageDirectory,
                cordova.file.cacheDirectory,
                cordova.file.dataDirectory,
                cordova.file.externalRootDirectory , 
                cordova.file.externalApplicationStorageDirectory,
                cordova.file.externalCacheDirectory,
                cordova.file.externalDataDirectory

            ];

Anyone has a solution. This works in api 22 broke >22

**Comment by jessemonroy650** [comment]
I have no solution, but my code is responding the same way. Null items found in the directory. 

**NOTE:** This is also effecting other plugins, like Media - which is my goal.  I'm working on more supporting data on this issue. I should post that information within the next 48 hours.

**Comment by NetZAL** [comment]
I am having the same issue, how to reslove?

**Comment by breautek** [comment]
Closing due to staleness.

Ensure you are waiting for the `deviceready` event before trying to access any plugin variables or APIs.
