### ISSUE TITLE
Cordova 8.0 file paths

### ISSUE THREAD

**Issue by rolinger** [apache/cordova-plugin-file#256]
I recently upgraded my environment from Cordova 7.1 to 8.0, and from Androi 6.5.4 to 7.1.1....after doing so, I notice the Android paths are not the same anymore.

My code file path is:
`    var filePath = cordova.file.applicationDirectory ;  // assets folders, preloaded`

And I put the files in `/myApp/platforms/android/assets` - but after the upgrade the file path no longer works as the app can't find the files.

Where should I be putting the files now?

**Comment by rolinger** [comment]
Can anyone please comment on this?  For Android, what is the filepath to put read-only files for `cordova.file.applicationDirectory` in Cordova 8.0 & cordova-android 7.1.1?

**Comment by rolinger** [comment]
PLEASE....can someone take 2 seconds to answer this issue.

What is the file path for `cordova.file.applicationDirectory` ?  I tried putting read-only json files in /projectRoot
/projectRoot/www
/projectRoot/platforms/android/assets 

And each time `cordova.file.applicationDirectory` can't find the json files.

**Comment by jcesarmobile** [comment]
New folder is `platforms/android/app/src/main/assets/www/`
But you shouldn't do any changes there, you should use the CLI and `cordova prepare` should copy your files from the root www to that other www
