### ISSUE TITLE
File becomes [object Object] in FormData

### ISSUE THREAD

**Issue by artuska** [apache/cordova-plugin-file#260]
The File object i get from the cordova-plugin-file in my Cordova application is not the same as File i get in browser (for example in FileList when i choose files from `<input type="file">`).

```
// i use cordova-plugin-filechooser to select a file 

window.fileChooser.open((uri: string) => {

    // `uri` is a `content://...`

    window.FilePath.resolveNativePath(uri, (path: string) => {
 
        // `path` is a `file://...`

        window.resolveLocalFileSystemURL(path, (entry: FileEntry) => {
            entry.file((file: File) => {
                let fd = new FormData();

                fd.append('image', file);

                console.log(fd.get('image'));
                console.log(fd.getAll('image'));
            });
        });
    });
});
```

Console.log outputs:

```
[object Object]
["[object Object]"]
```

but it should be:

```
File(36244)
[File(36244)]
```

Here is how cordova-plugin-file File object looks like:
<img width="505" alt="screen shot 2018-10-03 at 18 15 15" src="https://user-images.githubusercontent.com/1013856/46453512-92704880-c7aa-11e8-8a2b-6231e195cf36.png">

Here is how normal File object (from FileList from `<input type="file">`) looks like:
<img width="512" alt="screen shot 2018-10-03 at 18 10 23" src="https://user-images.githubusercontent.com/1013856/46453523-9d2add80-c7aa-11e8-9056-9e0f78d73bdb.png">

How can i get normal File (using cordova-plugin-file) to use it in FormData? I need this to send files to the server.

**Comment by artuska** [comment]
Well, it seems like i have to use Blob instead of File because Blob is original Blob and is not overridden by cordova-plugin-file as File is.

**Comment by janpio** [comment]
My guess for _why_ this is the way it is: Cordova's `File` was created before there was a standard `File` in the browsers, so back in the day someone created a "Cordova `File`".

**Comment by artuska** [comment]
Thank you! I resolved it by creating a Blob and sending it to the server — it works :)

**Comment by Polypants** [comment]
@artuska how exactly did you do that? I'm dealing with the same issue

**Comment by artuska** [comment]
@Polypants in my case the reason why some Androids cannot select files from the file system and returns `null` is `cordova-plugin-deeplinks` plugin which requires this string in `config.xml` file:

```
<preference name="AndroidLaunchMode" value="singleInstance" />
```

This preference ruins file select. I removed this line and file select is working now... but deeplinks are not working :) So you need to decide what you need most — file select of deeplinks on Android.

**Comment by artuska** [comment]
About the Blob. There are a lot of weird stuff here about the Blob in Cordova.

I used some custom file chooser (do not remember which exactly but you have to use custom file chooser, not <input type="file">) which returned `cdvfile` file path of the selected file → then I used `cordova-plugin-file` and it's `resolveLocalFileSystemURL` to get a link to the real file path → then I converted it to Blob and was able to sent it to the server the same way I sent File and then I wrote a comment here that everything works now... but all this was on Android API 21 emulator.

When I installed my app with all my Blob stuff to the Android phone (the phone which had issues with file select)... Cordova did not allowed me to send a Blob outside the Cordova environment. That's it. You cannot send Blob, Cordova will throw you the SSL error. I dunno what it is and what to do about it, so I just found other way to deal with broken file select (by removing AndroidLaunchMode preference as I wrote above here in comments) and just stopped further dealing with the Blob.

**Comment by judhisahoo** [comment]
> Thank you! I resolved it by creating a Blob and sending it to the server — it works :)

Hay bro.. can post your souultions here.. i  am trying to upload PDF using file chooser with formdata.. not getting soultions..

**Comment by victorpinheiro** [comment]
The problem still persists. Any workaround?
