### ISSUE TITLE
Unable to write multiple times in same file

### ISSUE THREAD

**Issue by ThibertT** [apache/cordova-plugin-file#262]
I am using this plugin to create a log file to log some of my app's logs in order to be able to debug some production errors (a service will email me the logs.txt).

Here is what I was trying to do ti be sure that this plugin is what I was looking for : 

- Create a logs.txt in "cordova.file.externalDataDirectory" folder without replace it if already exist (working perfectly)
- Write multiple lines in this logs.txt at multiple times (application lifecycle) (don't work...) 

**Here is my testing code :** 

```
this.platform.ready().then(() => {
       this.file.createFile(cordova.file.externalDataDirectory, 'logs.txt', false).then(() => { 
        console.log("Create new file logs.txt");
          for(let i = 0; i< 10; i ++){
            setTimeout(()=>{
              this.file.writeFile(cordova.file.externalDataDirectory,'logs.txt','helloWorld'+i+' \n',{ replace: false, append: true }).then(() => {      
                console.log("Write file OK");
              })
              .catch((err) => {
               console.error("Write file err : " +err);
              });
            }, 1000);
          }
        //If file already exist file.createFile() goes here :
        }).catch((err) => {
          console.log("File logs.txt already exist : " + err);
            for(let i = 0; i< 10; i ++){
              setTimeout(()=>{
              
                this.file.writeFile(cordova.file.externalDataDirectory,'logs.txt','helloWorld'+i+' \n',{ replace: false, append: true }).then(() => {      
                  console.log("Write file OK");
                })
                .catch((err) => {
                 console.error("Write file err : " +err);
                });
              }, 2000);
            }
        });;
       });
```

In my console output I can see ten "Write file OK", so writes process should be good. I was looking to find ten lines of "helloWorld"+i in the logs.txt file. But no...
Sometimes there is one line, sometimes three lines, sometimes two (never the same).

Should I need to close the file before writing in again ? Documentation on that plugin is quite not explicit and relevant.

Do you know any other plugin that will allow me to create a persistant file and write into it ?

Thank for your help !

**Comment by zcoffin86** [comment]
Your `for(...) { setTimeout(()=>{...}, 2000)}` is just going to run all of those anonymous functions almost simultaneously; you're doing simultaneous writes to the same file instead of waiting for each previous write to finish. I'm guessing you need to do each `writeFile()` call after the previous `writeFile()` promise has been resolved.

**Comment by breautek** [comment]
Closing this due to staleness. zcoffin86 comment above should resolve this issue. Unfortunately these are not streams, therefore, you need to wait for each chunk to be written, before writing more.
