### ISSUE TITLE
How to create a FileEntry?

### ISSUE THREAD

**Issue by zdd** [apache/cordova-plugin-file#263]
Most of the examples on the page use FileEntry, but it didn't mention how to create it.
I am wondering how can i invoke this method in code.
```
function readBinaryFile(fileEntry) {

    fileEntry.file(function (file) {
        var reader = new FileReader();

        reader.onloadend = function() {

            console.log("Successful file write: " + this.result);
            displayFileData(fileEntry.fullPath + ": " + this.result);

            var blob = new Blob([new Uint8Array(this.result)], { type: "image/png" });
            displayImage(blob);
        };

        reader.readAsArrayBuffer(file);

    }, onErrorReadFile);
}
```

**Comment by vikshv** [comment]
+1

**Comment by Lizard-King101** [comment]
trying to figure this out as well not sure why this isn't a higher priority as idk maybe it's the main point of the plugin . . .

**Comment by niccokunzmann** [comment]
I am doing research as this is also my problem.

You can use `DirectoryEntry.getFile()` to create a `FileEntry`
https://github.com/apache/cordova-plugin-file/blob/5e12b5e9f63b12aef5198e9a72ac8d7b8e834442/www/DirectoryEntry.js#L103

There is `resolveLocalFileSystemURL (uri, onSuccess, onError)`
https://github.com/apache/cordova-plugin-file/blob/5e12b5e9f63b12aef5198e9a72ac8d7b8e834442/www/resolveLocalFileSystemURI.js#L43

You can create a new FileEntry with these parameters: `name, fullPath, fileSystem, nativeURL`
https://github.com/apache/cordova-plugin-file/blob/5e12b5e9f63b12aef5198e9a72ac8d7b8e834442/www/Entry.js#L121

There are some hints [here](https://github.com/apache/cordova-plugin-file/blob/5e12b5e9f63b12aef5198e9a72ac8d7b8e834442/src/windows/FileProxy.js#L418):
```
    var srcFS = getFilesystemFromURL(src);
    var dstFS = getFilesystemFromURL(parent);
    var srcPath = pathFromURL(src);
    var dstPath = pathFromURL(parent);
```
and [here](https://github.com/apache/cordova-plugin-file/blob/5e12b5e9f63b12aef5198e9a72ac8d7b8e834442/src/windows/FileProxy.js#L457)
```
new FileEntry(
                            name,
                            tgtFsPath,
                            dstFS.name,
                            dstFS.makeNativeURL(tgtFsPath)
)
```
There are these:
https://github.com/apache/cordova-plugin-file/blob/5e12b5e9f63b12aef5198e9a72ac8d7b8e834442/src/windows/FileProxy.js#L914

After looking at this
https://github.com/apache/cordova-plugin-file/blob/5e12b5e9f63b12aef5198e9a72ac8d7b8e834442/src/windows/FileProxy.js#L974
I guess, the parameters look like this for a file in `/directory/file.txt`:
- name: `file.txt`
- fullPath: `/directory/file.txt`
- fileSystem: `fs.name`
- nativeURL: `fs.makeNativeURL(path)`

**Comment by wehe64** [comment]
full example in [the dox](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/#create-a-persistent-file)

**Comment by breautek** [comment]
Closing as I think the question has been answered. Thanks everyone.
