### ISSUE TITLE
Read image file as buffer

### ISSUE THREAD

**Issue by zdd** [apache/cordova-plugin-file#264]
I have get the file path of an image file on android device, how can i read it as binary buffer?
filePath = '/data/user/0/com.jiyuzhai.shufadaquan/cache/tmp_img-abc57fad8017314158eff0a367235c0d5080042548148907544.jpg' ? the example use fileEntry, but it didn't say how to init a FileEntry.

**Comment by breautek** [comment]
`FileReader.readAsArrayBuffer` method to read files into an array buffer (which is a binary buffer). 

[Docs](https://github.com/apache/cordova-plugin-file#store-an-existing-binary-file-) now have examples of how to handle binary data.
