### ISSUE TITLE
Don't override native window.File / window.FileReader (possibly via a preference)

### ISSUE THREAD

**Issue by asgoth** [apache/cordova-plugin-file#265]
I have a use case where I want to convert the cordova File object to a native File object. This is needed in order to submit a multipart request to a midtier server.

However, the original native File constructor is gone (overwritten by cordova-plugin-file).

Maybe consider using custom names, e.g. CordovaFile & CordovaFileReader?

**Comment by janpio** [comment]
Feel free to create a Pull Request on the plugin that changes this functionality in a backwards compatible way.

**Comment by elowes** [comment]
any progress?

**Comment by chr15m** [comment]
:+1:

**Comment by breautek** [comment]
duplicate: https://github.com/apache/cordova-plugin-file/issues/316
