### ISSUE TITLE
Write file inside applicationDirectory.

### ISSUE THREAD

**Issue by ankit18singh** [apache/cordova-plugin-file#267]
Hi,
I have gone through the doc, and it clearly mentions that applicationDirectory is ReadOnly.
But if there any way to replace existing files inside applicationDirectory like some assets file.
`Cordova Ionic plugin` is already doing it, by downloading and extracting the updated version to support hot-reloading of new updates in the app, and it is able to directly copy the file to applicationDirectory from a snapshot directory, how is it possible to replace/write/copy a single file inside the applicationDirectory.

Note: I noticed in doc it is also mentioned that 

> ReadOnly with restricted access. `Copying files in this directory is possible, but reading it directly results in 'file not found'`. Android also supports a special filesystem named "documents", which represents a "/Documents/" subdirectory within the "files" filesystem.

What does that mean, and what is the most appropriate way to copy file inside application directory.

Help needed.
Thanks in advance.

**Comment by janpio** [comment]
> Cordova Ionic plugin is already doing it, by downloading and extracting the updated version to support hot-reloading of new updates in the app, and it is able to directly copy the file to applicationDirectory from a snapshot directory, how is it possible to replace/write/copy a single file inside the applicationDirectory.

What plugin are you talking about? 
If this is possible there, just look at the code how it is doing this.

>> Copying files in this directory is possible, but reading it directly results in 'file not found'
> What does that mean

My guess: You can copy files from this directory to somewhere else, but can't read them directly to access them.

**Comment by ankit18singh** [comment]
You guessed it correctly, but is there any other way of doing it? Docs suggest we can copy into the applicationDirectory, but how? Is there any working code in your knowledge that I can refer?

**Comment by breautek** [comment]
Not sure which plugin you're talking about, nor am I really an expert in the inner workings of these kind of tools but my guess is they don't actually write to the assets directory, as I'm nearly certain that is read only.

Most hot reloads I've seen uses a webserver and has you pointing the cordova `<content src="">` to the webserver.

OR

They have JS code that evaluates changes and hot replaces runtime objects.
