### ISSUE TITLE
Small .csv file (<1 KB) created by this plugin fails to attach to email on Android

### ISSUE THREAD

**Issue by pdubuc** [apache/cordova-plugin-file#271]
Using this plugin, I generated a small .csv file and stored it in the Android device's internal file system. Then, I attempted to programmatically attach it to an email in the Gmail app, but the attaching fails.  I get an error because subsequent commands to attach the file are executing before the file is available on the phone's internal path: `/data/data/<app-id>/files/ Documents`.

This seems to be a timing issue because adding a 1-second `sleep()` delay before running the 'attach' command solved the problem and the .csv file gets attached.  Can anyone share a best practice, such as a "wait for the .csv file generation to complete", for delaying the execution of subsequent commands rather than using a `sleep()` function?

**Comment by breautek** [comment]
`FileWriter` has callback methods you can implement to be notified when the file writing is finished.

See the [example](https://github.com/apache/cordova-plugin-file#write-to-a-file-)
