### ISSUE TITLE
Can I overwrite the file in source web cordova (www) for updating source code

### ISSUE THREAD

**Issue by duchuy294** [apache/cordova-plugin-file#272]
I mean that I store update file in cloud and when user open up my's application then the lastest file in cloud will overwrite to www. So user always see the lastest update of app and not to rebuild the application.

Thank you very much.

**Comment by janpio** [comment]
That is not what `cordova-plugin-file` was made for, and it can not be used to achieve that.

There are plugins out there that do that: Ionic Pro has a [Live Deploy](https://ionicframework.com/docs/pro/deploy/) feature, Microsoft has [Cloud Push](http://microsoft.github.io/code-push/), now part of AppCenter and there are probably more out there if you google for them.
