### ISSUE TITLE
Cordova resolveLocalFileSystemURL doesn't return a file object on Windows

### ISSUE THREAD

**Issue by martinrcooper** [apache/cordova-plugin-file#277]
I know this has been asked before and closed:
File becomes [object Object] in FormData #260
but there was never a fix and the workarounds don't work for me, so I am opneing a new issue.
In my case, opening a file with resolveLocalFileSystemURL works in Android - I see [object File], but not in Windows 10 - I see [object Object]. This is a big deal for me as it apears to break my file upload in Windows 10 - see https://stackoverflow.com/questions/53670802/cordova-resolvelocalfilesystemurl-doesnt-return-a-file-object-on-windows
I currently can't see any way to upload a file on Windows 10 - the examples in the cordova-plugin-file documentation all use FileReader.readAsArrayBuffer which is not supported with on Windows 10 and I can't find any example on the internet using readAsBinaryString. I tried the example, using readAsBinaryString as a direct replacement for readAsArrayBuffer but the upload fails. Also cordova-plugin-file-transfer is deprecated so I don't want to use that (even if it works with Wndows 10).

**Comment by sambegin** [comment]
@martinrcooper I know it's kind of late but see [my recent comment](https://github.com/apache/cordova-plugin-file/issues/240#issuecomment-458566318). You are probably not the only one to get this.

**Comment by breautek** [comment]
The [Windows](https://github.com/apache/cordova-windows) platform is deprecated and is no longer supported making this issue obsolete.
