### ISSUE TITLE
Error just after installation, even before javascript import

### ISSUE THREAD

**Issue by vh13294** [apache/cordova-plugin-file#293]
# Bug Report

## Problem
after installation, build and run on android (tested on v7 and v9) then I got this error:

W/ResourceType: Invalid package identifier when getting bag for resource number 0x00000000
D/Capacitor: Starting BridgeActivity
W/System.err: java.lang.ClassNotFoundException: org.apache.cordova.file.FileUtils

I/System.out: Error adding plugin org.apache.cordova.file.FileUtils.
D/AndroidRuntime: Shutting down VM

### Command or Code

ionic cordova plugin add cordova-plugin-file
npm install @ionic-native/file
ionic capacitor run android -l

Github link [https://github.com/vh13294/ionic4_starter](url)
### Version information

-Ionic v4
-angular v7
- cordova-plugin-file v6.0.1
- android v7 to v9

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

I tried to remove this from config.xml and it builds with no error. However when using the pluggin another error occur which says could not find the plugin.

```
 <param name="onload" value="true"/>
```

```
<feature name="File">
    <param name="android-package" value="org.apache.cordova.file.FileUtils"/>
    <param name="onload" value="true"/>
 </feature>
```

**Comment by janpio** [comment]
Is this reproducible in a new, plain **Cordova** app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

If not, this sounds more like a Capacitor problem.

**Comment by vh13294** [comment]
fix using this command:
npx cap sync
