### ISSUE TITLE
file.applicationStorageDirectory returning wrong directory

### ISSUE THREAD

**Issue by andreddosantos** [apache/cordova-plugin-file#300]
Hello guys i'm using the plugin to get the application storage directory.

`file.applicationStorageDirectory ` is returning **"file:///data/user/0/..."**

According to the [documentation](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/#android-file-system-layout) it should be "/data/data/app-id/"

What is happening?
Can someone help me to understand?

And why do i have different behaviors for the same implementation?
sometimes returns one directory other the other... 

Kind regards 
André Lopes Santos

**Comment by janpio** [comment]
> And why do i have different behaviors for the same implementation?
> sometimes returns one directory other the other...

What does that mean? Does it change on the same device? Or on different devices? Or on differnet platforms?

**Comment by breautek** [comment]
Different devices will have different structures.

`/data/user/0` will appear on devices that support multiple users. `/data/data` should still exist as a symlink to `/data/user/0` however, but if it doesn't Cordova can't do anything about that, that's up to the phone manufacturer/OS.
