### ISSUE TITLE
requireCordovaModule problem

### ISSUE THREAD

**Issue by caiotarifa** [apache/cordova-plugin-file#307]
# Bug Report

## Problem

Trying to use this module with Cordova 9 and I get this message when I performed `cordova plugin add cordova-plugin-file`.

```
Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
```

### What is expected to happen?

The plugin needs to be added.

### What does actually happen?

Nothing, there's no plugin on `package.json` ou `config.xml`.

### Command or Code

```
$ cordova plugin add cordova-plugin-file
```

### Version information

- Cordova 9.0.0
- macOS 10.14.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by RajuDhami** [comment]
Downgrading to Cordova version 8 will solve the problem. Issue is with Cordova version 9 and above.

**Comment by epetre** [comment]
Why is this closed? It will have to work with Cordova 9 eventually.

**Comment by janpio** [comment]
> Why is this closed?

Because the user that created the issue also closed the issue.



> `Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

`requireCordovaModule` is used 0 times in the codebase of this plugin. I would say it is highly unprobable that this message is caused by this plugin then.

Or where do you think this plugin causes this problem @epetre?
