### ISSUE TITLE
iOS: /Library/NoCloud missing after restore

### ISSUE THREAD

**Issue by hohae** [apache/cordova-plugin-file#308]
My app stores its file in a directory structure under /Library/NoCloud for iOS. After restoring a backup to a new phone, the files are missing. 
It doesn't make a difference if I do a iTunes backup to my local computer or a iCloud backup. 

Is this directory part of any backup?

Regards,
Holger

**Comment by janpio** [comment]
What `cordova.file.xxx` constant are you using for that directory?

**Comment by breautek** [comment]
`/Library/NoCloud` are for files that doesn't require to be backed up. It does not sync with iTunes or iCloud.

See the [docs](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/#file-system-layouts) for more information. You probably want `/Documents` or `/Library/Cloud` instead.
