### ISSUE TITLE
File.readAsDataURL promise does not fullfill

### ISSUE THREAD

**Issue by amatrix85** [apache/cordova-plugin-file#309]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description

File.readAsDataURL promise does not fullfill

## Information

Good daytime,

I am writing an Ionic App which gets file from camera/gallery, writes it into folder (both work) and next must insert in into JSON structure (realized as interface, then converts with JSON.stringify). Right before sending query method reads file into string variable with following code (see below in apropriate section).

File exists. Code worked fine just once. But other times promise never been resolved at all.

It doesn't matter "AsWhat" it reads (ArrayBuffer, BinaryString or even Text) and even with strict path division as written in function reference (which I could found only in IDE's pop-up hint, according to which path is File.dataDirectory and file is remained part of fullpath) result is same (its absence).

### Command or Code

File.readAsDataURL(imagePath, imageName).then(res=>{
  console.log('It works.');
},err=>{
  console.log(err);
});

### Environment, Platform, Device

Target platform: Android API 25
Target device: Emulator, AGM A8 SE
Workstation: Ubuntu Studio Bionic Beaver with latest updates

Variable imagePath is, for example, file:///data/user/0//files/2b0d8450-14dc-44b3-ab28-322c5c2859e4 and imageName is Pasport_Famil_I._stranicza_s_fotografiej.jpg

### Version information

OpenJDK 8u191-b12-2ubuntu0.18.04.1
Ionic 4.12
Ionic file plugin 5.5.0
cordova-plugin-file 6.0.1 

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by amatrix85** [comment]
Solved. Problem was in forgotten custom code in src/index.html . Fixed.

**Comment by sumit1195** [comment]
q

**Comment by sumit1195** [comment]
> Solved. Problem was in forgotten custom code in src/index.html .

what part your forgot ?
