### ISSUE TITLE
cordova.file.* all are null ( ios )

### ISSUE THREAD

**Issue by NetZAL** [apache/cordova-plugin-file#313]
English:
I use my iphone6 to test the record, but I find when I use cordova.file.* all is null. But in android all is ok. such as cordova.file.tempDirectory in IOS is null. someone know what happens, thank you!

中文:
我用苹果六真机调试的时候, 我发现cordova.file.*下所有路径都是 null 值， 在安卓下的话就才几个才是null， 其他可以用。 请问谁知道啥原因? 谢谢

**Comment by janpio** [comment]
What code are you using to get `null`?

**Comment by rvirani1** [comment]
Yeah, I'm having the same issue. `window.cordova.file` has a bunch of keys that are all null, but only on iOS.

**Comment by NetZAL** [comment]
I solved this problem.
you just reduced version, when you run the command " cordova platform add ios ", you can run this command " cordova platform add ios@4.1.0 "




------------------ 原始邮件 ------------------
发件人: "Riaz Virani"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 晚上10:00
收件人: "apache/cordova-plugin-file"<cordova-plugin-file@noreply.github.com>;
抄送: "透析童年丶"<969807344@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/cordova-plugin-file] cordova.file.* all are null ( ios )(#313)




Yeah, I'm having the same issue. window.cordova.file has a bunch of keys that are all null, but only on iOS.

**Comment by breautek** [comment]
The constants will be null until `deviceready` event has fired.
