### ISSUE TITLE
Contributing guidelines are misleading

### ISSUE THREAD

**Issue by syonip** [apache/cordova-plugin-file#321]
CONTRIBUTING.md states I should open a JIRA issue at this link: http://cordova.apache.org/contribute/
But going there, it says:
"All Cordova issues should now be reported on GitHub. Our JIRA issue tracker has been closed, and new issues can no longer be opened there."

**Comment by janpio** [comment]
Thanks, good point. As this applies to all Apache Cordova repositories I created a global issue https://github.com/apache/cordova/issues/115 where this can be tracked.

Thanks for opening this issue!
