### ISSUE TITLE
Android: Using build-extras.gradle in Phonegap Build

### ISSUE THREAD

**Issue by GitToTheHub** [apache/cordova-plugin-file#325]
Hi,
I experienced that access to the assets-Directory is very slow, like you said in your doc. In the doc, i found the solution, to add a build-extras.gradle from the plugin, to solve the issue. Since I'm using Phonegap Build, i cannot add it to my Project in a normal way. Do you know a solution for Phonegap Build, so i can use the build-extras.gradle?
Thank you, for helping me :)

**Comment by janpio** [comment]
What did the Phonegap Build people say about this?

**Comment by GitToTheHub** [comment]
I thought you will ask this. I will ask them:)

**Comment by GitToTheHub** [comment]
Hi, i asked the Phonegap Build Community, but as expected, nobody is answering me ([see](https://forums.adobe.com/thread/2628854)). There is an old question from 2017 with the same topic ([see](https://forums.adobe.com/thread/2370960)), but still unreplied.
Maybe you have a hint for me to add the build-extras.gradle for Phonegap build, bacause my app needs 3 Seconds longer on Android to start, because I'm accessing the assets.
Thank you, for you help !

**Comment by janpio** [comment]
No experience at all with Phonegap Build, so no idea. Sorry.

**Comment by GitToTheHub** [comment]
Ok maybe someone else or do you have an other idea to make the assets dir access fast under android with phonegap build?

**Comment by ramonjsantiago** [comment]
I would also like to be able to add a build-extras.gradle to my Phonegap Build.
I've added a copy of it in every directory that I think is appropriate. It is sent to PhoneGap Build but never gets executed.

**Comment by breautek** [comment]
PhoneGap Build is out of service, so closing as obsolete.
