### ISSUE TITLE
FileEntry.file is not a function

### ISSUE THREAD

**Issue by koraysels** [apache/cordova-plugin-file#333]
# Bug Report

## Problem
given the example: 

```
function readFile(fileEntry) {
    fileEntry.file(function (file) {
        var reader = new FileReader();
      reader.onloadend = (evt: any) => {
        var voiceBlob: any = new Blob([evt.target.result], { type: 'audio/m4a' });
        console.log('fileBlob -> ' + fileBlob);
      };

      reader.onerror = (e) => {
        console.log('Failed file read: ' + e.toString());
      };
      reader.readAsArrayBuffer(file);

    }, onErrorReadFile);
}
```

### What is expected to happen?

`fileEntry.file` should work and the filereader should be able to read the file as ablob

### What does actually happen?

`fileEntry.file` is undefined.. the .file() function does not exist on FileEntry..

### Environment, Platform, Device
testen on ios 12 ipad

### Version information
mac osx
cordova 9 
file plugin 6.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
> `fileEntry.file` is undefined.. the .file() function does not exist on FileEntry..

That's not true:
https://github.com/apache/cordova-plugin-file/blob/e12935ced55ae5ec7019cc055bf1d7e13c1aed8d/www/FileEntry.js#L74-L90

In the context of this plugin, this method should be available.

How are you creating your `fileEntry`?

**Comment by koraysels** [comment]
I have a filepath of the sorts : `documents://audio.m4a`
And I have tried to use `resolveLocalFileSystemURL` but that throws an error code5. the file does exist because I can play it with Media plugin. 
 
I tried to do a readAsArrayBuffer on the pathname but that fails abviously.. I am a bit stuck..

**Comment by janpio** [comment]
> How are you creating your `fileEntry`?

**Comment by koraysels** [comment]
Actually I found it is a bug that more people are having this error code and it is a bug in cordova.. 

right now I figured it out for iOS by doing the following:

```
  window.requestFileSystem(window.LocalFileSystem.PERSISTENT, 0, async fs => {
          window.resolveLocalFileSystemURL(this.file.documentsDirectory, async dirEntry => {
            let justTheNameOfTheFile = filePathWeWantToRead.split('://')[1];

            dirEntry.getFile(justTheNameOfTheFile, { create: false, exclusive: false }, fileEntry => {
              console.log('fileEntry -> ' + fileEntry);
              this.readFile(fileEntry, resolve, reject); //this is the function of the first post
            });
          }, (error) => {
            console.error('something went wrong with resolving the file, trying to resolve without FilesystemURL');
            console.error(error);
          });
        });
```

Now this works in iOS when creating the file with Media.create in the `cordova.file.documentsDirectory` So that is solved.,. only android won't work yet..

**Comment by janpio** [comment]
Sorry, you have to elaborate a bit here, I don't understand.

**Comment by koraysels** [comment]
Well as seen here in this issue there is a common error when trying to read a full filepath.. So As described in (this answer)[https://github.com/apache/cordova-plugin-file/issues/289#issuecomment-477954331] I now go to the directory and then get the file without the full path from the directory entry.. This works.. for both android and ios. Directly getting the full file does not seem to work.. 

> #289

**Comment by janpio** [comment]
So creating your `fileEntry` you encountered an error code 5, which caused it to be empty and thus your code not working. Correct?

**Comment by koraysels** [comment]
NO, trying to get a file entry using the full path gives an error code 5. becuase it has `://` inb it, it throws an error code 5.

**Comment by janpio** [comment]
So exactly what I wrote, with the added information that it was caused by using the full path (which is a bug) - right?
