### ISSUE TITLE
Xhr requests to local files

### ISSUE THREAD

**Issue by Nashorn** [apache/cordova-plugin-file#336]
If there are requests to relative paths via ajax/fetch and inline declarative paths, are they handled automatically or does the request need to be intercepted and pass through the API?

**Comment by brodybits** [comment]
Can you post any samples?

**Comment by breautek** [comment]
It's not recommended to use AJAX on file paths, there is a lot of browser security that you have to jump through hoops.

It is possible on cordova-ios@6 and cordova-android@10 with schemes enabled, but is restricted to the app's assets directory.
