### ISSUE TITLE
Android file problems

### ISSUE THREAD

**Issue by NjnuTZhou** [apache/cordova-plugin-file#338]
I am trying to integrate cordova webapp into native android,However the cordova-plugin-file always reports "Channel not fired: onFileSystemPathsReady", so the deviceonready event cannot execute.I have granted read-write-external-file authority to apps. so please tell me how the problem appears and how to fix it.
Thank you!

**Comment by Nashorn** [comment]
I have had this happen to me on last project when using code-push plugin, it installs the cordova-plugin-file which i think causes the 'deviceready' event to never fire after 5 seconds as well as onFileSystemPathsReady. Would love to know a solution.

**Comment by chengda** [comment]
I have the same issue. Now I have to remove this plugin temperarily. Please help me to fix it. Thanks.

**Comment by breautek** [comment]
Likely caused by a plugin not initialising or taking a very long time to initialise properly.

You may be able to gain more insights if you look at logcat.
