### ISSUE TITLE
Create File and createNewDirectory not created - "FILE NOT FOUND" error

### ISSUE THREAD

**Issue by ManjuVasi** [apache/cordova-plugin-file#340]
# Bug Report

### What is expected to happen?
A new folder to save the log text file needs to be created in device storage.

### What does actually happen?
But only myfiles->Android->Data->com.XXX.XXX ->files and temp are created. No further folder is created.

### Command or Code

var createNewDirectory = function (isExternal, parentDirectory,
                directoryName, onSuccess, onError) {
      //set path for device.
            var path = folderPath(isExternal);
            if (path === 2) {
                return path;
            }
  path = path + parentDirectory;

            if ($cordovaFile.checkDir(path, directoryName)) {
                $cordovaFile.removeDir(path, directoryName)
            }
/*****till here its working fine*****/
            var status = $cordovaFile.createDir(path, directoryName).then(/*******Always error fn is caled***/
                    function (success) {
                        onSuccess(success);
                        return 0;
                    }, function (error) {
                onError(error);
                // Log error
                return 1;
            });
            return status;

        };
Always error function is called.

cordovaService.createNewDirectory(true, "XXX/", "log"
                , onCreateLogSuccess, onCreateLogError);

### Environment, Platform, Device
Android 8.0.0 APK  but same code  works in Android 6 and iOS.

### Version information
Android 8.0.0 in Cordova build the functionality is failing. But the APK generated with Android 6 it was working and in iOS also its working.

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
Not all paths are writable, such as `cordova.file.externalRootDirectory`, can you provide the file path to where you're attempting to write to?

Also please include your code that uses the cordova file plugin APIs.

**Comment by breautek** [comment]
stale
