### ISSUE TITLE
getFreeDiskSpace wrong on Android

### ISSUE THREAD

**Issue by crawft** [apache/cordova-plugin-file#342]
# Bug Report

### What is expected to happen?
Reported free disk space on my device in settings is 90+Gb

### What does actually happen?
getFreeDiskSpace reports 87MB free and doesn't appear to change

### Command or Code
getFreeDiskSpace

### Environment, Platform, Device
Huawei P20 Pro, Android 8.1

### Version information
plugin v6.0.2
Cordova 9.0.0

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Have you installed an external storage, like an SD card? The code command says:
```
                    // The getFreeDiskSpace plugin API is not documented, but some apps call it anyway via exec().
                    // For compatibility it always returns free space in the primary external storage, and
                    // does NOT fallback to internal store if external storage is unavailable.
```

**Comment by crawft** [comment]
Having checked another plugin's result , it looks like you're reporting in MB when the docs I read said bytes
