### ISSUE TITLE
Android 10

### ISSUE THREAD

**Issue by azn1viet** [apache/cordova-plugin-file#345]
# Bug Report
- couldn't read/write files
## Problem
- crashed

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by azn1viet** [comment]
I found the issue of out dated plugin named "cordova-plugin-background-mode" that'd crash Android 9/10. You might have some of the out dated plugins in your projects that would cause issues, please check them and make a new project from scratch would help.
