### ISSUE TITLE
iOS 13 file input does not upload video from library

### ISSUE THREAD

**Issue by marensas** [apache/cordova-plugin-file#351]
## Problem
iOS 13 file input does not upload video from library
### Description
<input type="file" /> strangely accepting video from library. The file size is 0, parsing crashes. Direct video filming/uploading works ok. Photos direct/library are ok. Same project code from safari browser works ok.

When debugging APP in safari, I can edit HTML and add pure `<input type="file" />`, upload video from library, console input by command `document.getElementById(123).files` and see that `fileSize: 0`. 

### Environment, Platform, Device
IOS 13 ( or 13.1.2 ) Iphone X ( any ). Latest plugin versions.

**Comment by sutineeangs** [comment]
same problem

**Comment by ejlocop** [comment]
Hello, I experienced the same problem but I was able to nailed down what the issue was.
You must have a permission to acccess the library first before you can upload the video file to your server.

**Comment by sutineeangs** [comment]
> Hello, I experienced the same problem but I was able to nailed down what the issue was.
> You must have a permission to acccess the library first before you can upload the video file to your server.

Thank you.
I fixed it using cordova-plugin-photo-library and called cordova.plugins.photoLibrary.requestAuthorization().

**Comment by sutineeangs** [comment]
> Hello, I experienced the same problem but I was able to nailed down what the issue was.
> You must have a permission to acccess the library first before you can upload the video file to your server.
@ejlocop 
Thank you.
I fixed it using cordova-plugin-photo-library and called cordova.plugins.photoLibrary.requestAuthorization().

**Comment by marensas** [comment]
I granted permissions with `cordova.plugins.diagnostic` plugin:

https://github.com/dpa99c/cordova-diagnostic-plugin#getcamerarollauthorizationstatus
https://github.com/dpa99c/cordova-diagnostic-plugin#requestcamerarollauthorization

Closing.
