### ISSUE TITLE
how can i solve: [phonegap] [console.warn] Could not load worker SecurityError: Failed to construct 'Worker': Access to the script at 'blob:file%3A///2b3de33d-22f8-4ff0-b883-02d1ccfc511f' is denied by the document's Content Security Policy.

### ISSUE THREAD

**Issue by Programmeryusuf** [apache/cordova-plugin-file#355]
im always getting this error whenever i tried to create,edit, read or do any thing with cordova-plugin-file.
[phonegap] [console.warn] Could not load worker SecurityError: Failed to construct 'Worker': Access to the script at 'blob:file%3A///2b3de33d-22f8-4ff0-b883-02d1ccfc511f' is denied by the document's Content Security Policy.
is there any solution?

**Comment by breautek** [comment]
You have an incorrect CSP configuration. 

The `script-src` section of `Content-Security-Policy` meta tag needs to have `blob:`

You can read more at https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/#content-security-policy
