### ISSUE TITLE
plugin uses uses unchecked or unsafe operations. on android

### ISSUE THREAD

**Issue by REPTILEHAUS** [apache/cordova-plugin-file#359]
Can no longer run my app as of today, issue below:
```
android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/file/AssetFilesystem.java:
uses unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.
```

**Comment by breautek** [comment]
Please fill the bug report form completely.

https://github.com/apache/cordova-plugin-file/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

Thank you.

**Comment by REPTILEHAUS** [comment]
Sorry but Im trying to move away from Cordova so dont have time to do extensive tests, I can however confirm that I fixed/resolved this build issue by adding the following above your class which will do for now for my case

```
@SuppressWarnings("unchecked")
public class AssetFilesystem extends Filesystem {
```

**Comment by breautek** [comment]
Closing because unable to reproduce this with the latest versions.
