### ISSUE TITLE
Creating new files using dynamic names

### ISSUE THREAD

**Issue by jvidalgz** [apache/cordova-plugin-file#360]
Hello, I'm trying to create new files using string templates, but unsuccessfully. I need to generate new file names per file, when I pass **filename** to **fs.root.getFile** always get a undefined value. Here is my code:

```
window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, (fs) => {                    
          const filename = `${filename} - ${date}.xlsx`                
          fs.root.getFile(filename, { create: true, exclusive: true }, function (fileEntry) {
          console.log("fileEntry is file?" + fileEntry.isFile.toString());                      
          writeFile(fileEntry, new Blob([response.data], { type: 'application/xlsx' }));
            }, reject());
     }, reject());
```
cordova and cordova-plugin-file are dependencies of a vue.js application

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by breautek** [comment]
stale
