### ISSUE TITLE
cordova-file-plugin crashing

### ISSUE THREAD

**Issue by FredGr** [apache/cordova-plugin-file#372]
I am trying to use the Cordova-Plugin-File to save a persistant file on the internal storage of an Adroid tablet.
The application crashes with the following messages :
I/chromium(32554): [INFO:CONSOLE(57)] "[RECV] - File system open: persistent", source: file:///android_asset/www/js/aexsensor-util.js (57)
I/chromium(32554): [INFO:CONSOLE(57)] "[RECV] - FileEntry is file?true", source: file:///android_asset/www/js/aexsensor-util.js (57)
I/chromium(32554): [INFO:CONSOLE(57)] "[RECV] - fileWriter Created:", source: file:///android_asset/www/js/aexsensor-util.js (57)
F/chromium(32554): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
E/chromium(  326): [0118/223044.477978:ERROR:memory_map.cc(159)] format error
E/chromium(  343): [0118/223045.804149:ERROR:memory_map.cc(159)] format error
10:36
I tried both window.requestFileSystem(window.PERSISTENT, 0, function (fs)  and window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function (fs)
But none of the works.
The craches happen in the cordova.js file at
10:37
`var callbackId = service + cordova.callbackId++
 argsJson = JSON.stringify(args);
    if (success || fail) {
        cordova.callbacks[callbackId] = {success:success, fail:fail};
    }`
Any idea how to solve this ?

**Comment by breautek** [comment]
Please edit your issue (or close this one and create a new one) and fill out the issue template. It provides us with necessary details to provide insight.

**Comment by timbru31** [comment]
Closing due to lack of feedback. If the issue persists, please open a new issue and follow the issue template, thanks!
