### ISSUE TITLE
the value of cordova.file.externalRootDirectory  return null

### ISSUE THREAD

**Issue by ctrlands** [apache/cordova-plugin-file#382]
vue+cordova, when i build the app with cordova, and then open the app first time(gived permissions), the value of **cordova.file.externalRootDirectory**  return **null**, after close app and open app again, the value is normal，what'wrong ?
![270DF67E-78BF-41ca-AEA4-05A5DE22589B](https://user-images.githubusercontent.com/29942027/77719209-b4552f00-701f-11ea-9181-981e7c4748fa.png)

**Comment by breautek** [comment]
You need to declare the "extra filesystems"

```
<preference name="iosExtraFilesystems" value="library,library-nosync,documents,documents-nosync,cache,bundle,root" />
<preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets,root" />
```

By default, the above should be already set, unless if you have overwritten in.

https://github.com/apache/cordova-plugin-file#configuring-the-plugin-optional

**Comment by timbru31** [comment]
Closing due to missing issue template and a potential solution by Norman. If the issue persists, please create a new ticket and follow the issue template. Thanks!

**Comment by Fransebas** [comment]
Hey @ctrlands did you solve this? I have the same issue
