### ISSUE TITLE
Download Apple hosted on-demand tagged resources from Cordova Webview

### ISSUE THREAD

**Issue by gabriele-sacchi** [apache/cordova-plugin-file#385]
Hi,
I'm digging around Apple documentation about [on-demand resources](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/IntrotoHostingODR.html#//apple_ref/doc/uid/TP40015083-CH17-SW1) but I can't find this information..

Is it possible to fetch via Javascriipt, from a WKWebView, an asset (eg. image, Javascript bundle) hosted on Apple servers as on-demand tagged resource?

My intent, in order to not affect the App final bundle size, is to publish some (big) HTML+JS games on their servers so that they can review it (so that it's not "injected code" that is against their guidelines) and then fetch them via Javascript XHR requests or using calls from the native layer of the App through a Cordova/PhoneGap/Ionic bridge.

This is what we need to achieve due to business constraints. Is it feasible?

-----

In my specific case, I would use the Cordova plugin [cordova-plugin-file](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/) to fetch/download the bundle with the additional HTML page to display.

Here is this question raised on SO: https://stackoverflow.com/questions/60955952/download-apple-hosted-on-demand-tagged-resources-via-javascript
I will reward with a 100 bounty whoever can help me achieve that.
Many thanks!

**Comment by gabriele-sacchi** [comment]
I had to write a custom cordova plugin to fetch ODR resources before being able to load them from the file system.

**Comment by noxiousmobile** [comment]
Hello @gabriele-sacchi I am doing the same stuff, can you assist me with some stuff? I am into a lot of learning at the moment, specifically about the Swift stuff.
