### ISSUE TITLE
Issue with version 6.0.2 when using Xcode 11.4 and iOS 13.4

### ISSUE THREAD

**Issue by anitha-suraj** [apache/cordova-plugin-file#389]
# Bug Report
We were using cordova-plugin-file version 6.0.1 earlier.
Currently we have upgraded to version 6.0.2 in our mobile application.

When we sign our app on macOS Catalina, using Xcode 11.4 and iOS 13.4, the build fails with a Lexical or Preprocessor issue

## Problem
Error messages:
.../ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:9: AssetsLibrary is deprecated and is not available when building for Mac Catalyst. Consider migrating to Photos instead, or use `#if !TARGET_OS_MACCATALYST` to conditionally import this framework, first importing TargetConditionals.h if necessary.

.../ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:9: 'AssetsLibrary/ALAsset.h' file not found

We know that this issue is caused by the cordova-plugin-file version because when we downgrade to 6.0.1 version, then the build is succeeding.

### What is expected to happen?
The build to succeed.

### What does actually happen?
Build fails.

## Information
![ios-build-issue](https://user-images.githubusercontent.com/64072985/79859322-7369f380-83ee-11ea-8b9e-489bfa4501a3.png)

### Command or Code
ios build on xcode

### Environment, Platform, Device
macOS Catalina, using Xcode 11.4 and iOS 13.4

### Version information
Cordova CLI - 9.0.0 (cordova-lib@9.0.1)
cordova-ios - 5.0.1
macOS Catalina
Xcode 11.4 
iOS 13.4

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by anitha-suraj** [comment]
Please note that the issue occurs when we try to sign and upload our app to app store.
'cordoa build ios' will succeed.

**Comment by erisu** [comment]
The error message you are showing in the ticket description:

>Error messages:
.../ios/CordovaLib/Classes/Public/CDVURLProtocol.m:20:9: AssetsLibrary is deprecated and is not available when building for Mac Catalyst.

is coming from the `cordova-ios` platform and is not related to this plugin `cordova-plugin-file`.

Additionally, the `CDVURLProtocol` file has been removed from the master branch. The next Cordova iOS major release (6.x) will not have the CDVURLProtocol and AssetsLibrary. 

There is no given ETA on release date as of yet.

https://github.com/apache/cordova-ios/pull/783
