### ISSUE TITLE
Check if file exists on Windows

### ISSUE THREAD

**Issue by maxborgatti** [apache/cordova-plugin-file#395]
Is there a way to check if a file exists on Cordova Windows platform root? Trying on Ionic on Windows 10 with no success:

`        this.file.checkFile('C:\test\\', 'testFile.exe')
          .then(() => {
            // TODO: stuff
          })
          .catch((err) => {
            // TODO: stuf
          });`

no way also using slashes (e.g. C:/test/) or dataDirectory.

Any support will be very very appreciated.

**Comment by breautek** [comment]
The [Windows](https://github.com/apache/cordova-windows) platform is deprecated and is no longer supported making this issue obsolete.
