### ISSUE TITLE
window.isFilePluginReadyRaised undefined and filePluginIsReady event doesn't fire

### ISSUE THREAD

**Issue by barakataboujreich** [apache/cordova-plugin-file#399]
hello, 
i need to read files from the device at the start of my app launch, and according to Chrome quirks Chrome filesystem is not immediately ready after device ready event.

so i tried using filePluginIsReady event, but this event does not fire, even when the filesystem is ready and i am able to read files.

i tried to subscribe to the event at the first page index.html, i tried to subscribe to the event at $(document).ready, i tried to subscribe to the event at deviceready event, but nothing worked for me.

also when i try to call window.isFilePluginReadyRaised i get undefined in console.

i am using:
cordova-plugin-file: 6.0.2
cordova: 9.0.0
android: 8.0.0

**Comment by breautek** [comment]
I believe `filePluginIsReady` is a browser platform thing only, not an android thing.

If you're using the browser platform, then please include the browser platform version and the browser version you're observing the issue.

**Comment by barakataboujreich** [comment]
oh okay, my bad.

then on android/IOS the plugin should be ready on deviceready event ?

**Comment by breautek** [comment]
> then on android/IOS the plugin should be ready on deviceready event ?

Correct.

**Comment by breautek** [comment]
At least i never used `isFilePluginReadyRaised` in my apps. I almost closed this ticket saying it isn't a cordova thing, but then I doubled check 😂😅

That event is listed under browser quirks.

Do let me know if this clears stuff up
