### ISSUE TITLE
Get lastModifiedDate from local file.

### ISSUE THREAD

**Issue by klochko7** [apache/cordova-plugin-file#407]
Hi all ! Could anyone suggest please, is it possible to get date when file was created ? I copy file to my phone from desktop and property lastModifiedDate returned me time when I copy file to the folder but not when file was created.

```
    win.resolveLocalFileSystemURL(this.settingsProvider + this.settingsProvider.settings.folder + '/' + result[i].name, function(fileEntry) {

                        fileEntry.file(function(file) {

                          console.log("capture file", file.lastModifiedDate);

                        },    err => {
                          resolve(false);

                        });

                      },  err => {
                        resolve(false);

                      });
```

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
