### ISSUE TITLE
XLSX.writeFile is not working in angular to cordova app

### ISSUE THREAD

**Issue by Nishant05Chauhan** [apache/cordova-plugin-file#418]
Here is my code which i have implemented in Angular project

 

>  fileName = 'RequestReportExcelSheet.xlsx';
  exportexcel(): void {
    /* table id is passed over here */
    let element = document.getElementById('reportTable');
    const ws: XLSX.WorkSheet = XLSX.utils.table_to_sheet(element);   
    ws['!cols'] = [];
    ws['!cols'][5] = { hidden: true };
    /* generate workbook and add the worksheet */
    const wb: XLSX.WorkBook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
    //console.log(wb);
    /* save to file */
    XLSX.writeFile(wb, this.fileName);
  }

Also I have added the 'cordova plugin add cordova-plugin-file' this plugin but not able to download the xlsx file

**Comment by breautek** [comment]
We cannot provide assistance without knowing the information requested in the issue form. Additionally, Cordova doesn't have a `XLSX` namespace, this looks a third-party library to me.

> Also I have added the 'cordova plugin add cordova-plugin-file' this plugin but not able to download the xlsx file

Also worth noting that this plugin doesn't download files, it provides an API to write to or read from disk. It assumes you have that data locally already.
