### ISSUE TITLE
cordova resolveLocalFileSystemURI is deprecated. Please call resolveLocalFileSystemURL instead.

### ISSUE THREAD

**Issue by Suryalg** [apache/cordova-plugin-file#420]
# Bug Report

### What is expected to happen?
Like previously the plugin was working fine and previous version of app is fine but when I am building app now the error comes

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Generally speaking when a method is deprecated, it's because it has fundamental flaw. So the only advice I can give with the provided information is to refactor your code to use `resolveLocalFileSystemURL`.

Please fill the remaining information for further help.

**Comment by breautek** [comment]
Closing as stale.
