### ISSUE TITLE
Error thrown when accessing parent folder of cordova.file.externalApplicationStorageDirectory on Android 11

### ISSUE THREAD

**Issue by WeaponX86** [apache/cordova-plugin-file#422]
# Bug Report

## Problem
We can't verify all parent folders of cordova.file.externalApplicationStorageDirectory exist on Android 11

window.resolveLocalFileSystemURL('file:///storage/') // WORKS
window.resolveLocalFileSystemURL('file:///storage/emulated/') // FAILS
window.resolveLocalFileSystemURL('file:///storage/emulated/0/') // WORKS

### What is expected to happen?
Calling window.resolveLocalFileSystemURL('file:///storage/emulated/') should return a DirectoryEntry

### What does actually happen?
Calling window.resolveLocalFileSystemURL('file:///storage/emulated/') throws error code 1

Output on Pixel 1 with Android 10
![Android 10 output](https://user-images.githubusercontent.com/1253059/94062518-c9cfc980-fdb4-11ea-9510-a4c7b9c4f334.png)

Output on Pixel 3 with Android 11
![Android 11 output](https://user-images.githubusercontent.com/1253059/94062535-ce947d80-fdb4-11ea-9146-80da6a6dab3c.png)

## Information
For our app we store all saved files inside of cordova.file.externalApplicationStorageDirectory.

Ex. cordova.file.externalApplicationStorageDirectory + '/photos/123/'
Ex. cordova.file.externalApplicationStorageDirectory + '/photos/456/'
Ex. cordova.file.externalApplicationStorageDirectory + '/assets/123/'
Ex. cordova.file.externalApplicationStorageDirectory + '/assets/456/'

If I want to copy a file from say
cordova.file.externalApplicationStorageDirectory + '/photos/123/abc.jpg'
to 
cordova.file.externalApplicationStorageDirectory + '/photos/456/def.jpg'

We recursively verify each folder exists from file:// up to see if any folders need created. On Android <10 this has worked fine. 

I tried adding android:requestLegacyExternalStorage="true" but it doesn't help.

### Command or Code
cordova create myApp
cordova platform add android

[Modify config.xml & index.js](https://gist.github.com/WeaponX86/6a44b481064a8c5366411923e723bcb1)

cordova build android --debug

### Environment, Platform, Device
Pixel 1 - Android 10
Pixel 3 - Android 11

### Version information
Cordova 10.0.0
cordova-android 9.0.0
macOS 10.15.6
npm 6.14.8
android-minSdkVersion ="22"
android-targetSdkVersion ="29"
cordova-plugin-file spec="6.0.2"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mirko77** [comment]
@WeaponX86 I have the same issue, any workaround?

**Comment by WeaponX86** [comment]
> 
> 
> @WeaponX86 I have the same issue, any workaround?

Nope. Ended up having to change my recursion method from starting at the root to starting with the full path and working down to the root and hoping it never hits this path.

`	/**
	* Create a nested folder from a string in one of the standard filesystem locations
	* 
	* @public
	* @memberOf FileApi#
	* @param {string} sPath - The absolute folder path (a/b/c)
	* @param {function} fnSuccess - Success callback (object)
	* @param {function} fnFail - Error callback
	*/
	function createDirectoryAny(sPath, fnSuccess, fnError){
		
		console.log('FileApi: createDirectoryReverse - sPath: ' + sPath);
	
		//var aPath = sPath.split('/'); // Doesn't handle protocol correctly
		var oPath = Common.splitPath(sPath);
		//console.log(oPath);
		
		var sRoot = oPath['sRoot'].replace('///','//'); // Remove extra slash
		var aPath = oPath['aPath'];
		
		aPath.unshift(sRoot); // Append root to start of array
		
		//console.log('aPath',aPath)
		
		// RECURSIVE
		var fnCreate = function(directoryEntry,aPathTemp){
			
			//console.log('FileApi: createDirectoryReverse > fnCreate directoryEntry',directoryEntry);
			
			//console.log(aPathTemp);
			var sFolder = aPathTemp.shift(); // Affects aPath
			
			var sNewPath = directoryEntry.nativeURL + sFolder;
			
			// On Android 11, if the folder already exists, calling getDirectory will throw an error

            //console.log('FileApi: createDirectoryReverse > fnCreate > resolve not found: ' + sNewPath);

            directoryEntry.getDirectory(sFolder, {
                create : true,
                //exclusive: false
            }, function(childDirectoryEntry) {
                //console.log('FileApi: getDirectory success ' + childDirectoryEntry.fullPath);
                //console.log(directoryEntry);

                if (aPathTemp.length > 0){
                    fnCreate(childDirectoryEntry, aPathTemp);
                } else {
                    if (typeof(fnSuccess) == 'function'){
                        fnSuccess(childDirectoryEntry);
                    }
                }
            }, function(error){
                console.error('FileApi: createDirectoryReverse > getDirectory failed to create folder: ' + sFolder + ' under: ' + directoryEntry.fullPath + ' error code: ' + error.code);

                if (typeof(fnError) == 'function'){
                    fnError();
                }
            });
		};
		

		var fnResolve = function(iIndex){
			var sSubPath = aPath.slice(0,iIndex).join('/'); // Slice uses 1 index, not zero index
			
			if (iIndex > 1) sSubPath += '/'; // Append slash to end if not at root
			
			//console.log('fnResolve iIndex: ' + iIndex + ' sSubPath: ' + sSubPath);
			
			resolve(sSubPath,
			function(oEntry){
				//console.log('FileApi: createDirectoryAny > fnResolve path found: ' + sSubPath);
				
				fnCreate(oEntry, aPath.slice(iIndex)); // Break recursion
			},
			function(){
				if (iIndex > 1){
					fnResolve(iIndex-1);	
				} else {
					console.error('FileApi: createDirectoryReverse > fnResolve not found: ' + sSubPath);
					
					// No valid parent folder found
					if (typeof(fnError) == 'function'){
						fnError();
					}
				}	
			});
		}
		
		// ATTEMPT to resolve the full path
		resolve(sPath,function(oTarget){	
			console.log('FileApi: createDirectoryAny path already exists: ' + sPath);

			fnSuccess(oTarget);
		},function(){
			fnResolve(aPath.length); // Find the first parent path that already exists
		});
	}`

**Comment by breautek** [comment]
The Scoped Filesystem changed introduced in API 29 causes certain directories to become inaccessible. Attempting to read them generally results in simply file not found error (e.g. Error code 1)

https://github.com/apache/cordova-plugin-file/blob/6bab8817e3c14ea7caea7e0a2c9962605103f353/www/FileError.js#L31

I suspect anything up from external root or application root directory will be "out of bounds" for apps to read. Unfortunately, Google isn't clear on which directories specifically will become inaccessible.

**Comment by breautek** [comment]
> he externalRootDirectory directory is no longer a writable path with the Android's new filesystem. Google doesn't explicitly say which paths are no longer accessible, but it does [vaguely](https://developer.android.com/about/versions/11/privacy/storage#migrate-data-for-scoped-storage) say that some paths that used to be writable will no longer be accessible.

>>If your app uses the legacy storage model and previously targeted Android 10 or lower, you might be storing data in a directory that your app cannot access when the [scoped storage](https://developer.android.com/training/data-storage#scoped-storage) model is enabled...

https://github.com/apache/cordova-plugin-file/issues/408#issuecomment-1126059587

For this reason, I'm closing as won't fix.
