### ISSUE TITLE
cordova.file.applciationDirectory has wrong URL scheme on windows10

### ISSUE THREAD

**Issue by breminnyi** [apache/cordova-plugin-file#431]
# Bug Report
Field cordova.file.applicationDirectory returns wrong URL scheme for windows10 platform: `ms-appx:///` instead of `ms-appx-web:///`.

### What is expected to happen?
Correct URL to file, that starts from `ms-appx-web:///` if platform is windows10, file is loaded successfully.

### What does actually happen?
URL starts from `ms-appx:///` and file wasn't loaded.

### Command or Code
Create empty cordova project: `cordova create`
Add windows platform: `cordova platform add windows`
Add the plugin: `cordova plugin add cordova-plugin-file`

Also put access tag in config.xml file: `<access origin="*" />` (maybe it isn't necessary, IDK)

Now add some code into **_www/js/index.js_** `onDeviceReady` function: 
`var img = new Image();`
`img.src = cordova.file.applicationDirectory + 'www/img/logo.png';`
`var div = document.getElementsByClassName('app')[0];`
`div.appendChild(img);`

Run the application and observe the actual result.

### Workaround
Replacing all occurrences `ms-appx:///` with `ms-appx-web:///` in file `cordova-plugin-file/src/windows/FileProxy.js` should fix the problem.
But I'm interested in proper fix.

### Environment, Platform, Device
windows10

### Version information
Cordova CLI version:
`9.0.0 (cordova-lib@9.0.1)`
Plugin version:
`cordova-plugin-file 6.0.2 "File"`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
[Windows platform](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
