### ISSUE TITLE
[Android] content:// to file://storage does not get resolve

### ISSUE THREAD

**Issue by indraraj26** [apache/cordova-plugin-file#443]
# Bug Report

## Problem
When you take pdf anyother file from download you get URI with content://. So in order to resolve i use this package to get file URI path https://www.npmjs.com/package/cordova-plugin-filepath

### What is expected to happen?
It should resolve and return file detail

### What does actually happen?
It returns error code: 1 // not found 

## Information

chrome://inspect
![image](https://user-images.githubusercontent.com/23274631/101600543-779c5d00-3a21-11eb-8f2f-f4ac4667cacf.png)

### Command or Code

```
const options: CameraOptions = {
          quality: 50,
          destinationType: this._camera.DestinationType.FILE_URI,
          mediaType: this._camera.MediaType.ALLMEDIA,
          sourceType: this._camera.PictureSourceType.SAVEDPHOTOALBUM,
          saveToPhotoAlbum: false,
        };
```
```
 if (file.indexOf("content://") > -1) {
          console.log("content //", file);
          window.FilePath.resolveNativePath(file, (success) => {
            console.log(success, "content");
            window.resolveLocalFileSystemURL(success, (fileEntry) => {
              console.log(fileEntry, "fileEntry");
              fileEntry.file((finalFile) => {
                console.log(finalFile, "resolve");
                resolve(finalFile);
              });
            });
          });
        }
```

### Environment, Platform, Device

All Android version i think so btw currently i am testing on Android 10 

### Version information

Cordova CLI       : 10.0.0
Cordova Platforms : android 9.0.0

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

```

**Comment by breautek** [comment]
Can you try to parse out `/storage/emulated/0/` so you're full url looks something like `file:///Downloads/dummy.pdf`.

See https://github.com/apache/cordova-plugin-file#upgrading-notes for the why.

**Comment by indraraj26** [comment]
Repo: https://github.com/indraraj26/cordova-camera-fast-click/tree/content-file-path
Branch: content-file-path

Android 7 vs Android 10
![image](https://user-images.githubusercontent.com/23274631/102103633-3e198680-3e53-11eb-8830-a2359673f79f.png)

**Comment by indraraj26** [comment]
Repo to reproduce: https://github.com/indraraj26/cordova-camera-fast-click/tree/content-file-path
Branch: content-file-path
On Android 10 it returns code 1 error i.e file not found

Android 7 vs Android 10
![image](https://user-images.githubusercontent.com/23274631/102104433-31496280-3e54-11eb-9b25-9ae88f04519b.png)

**Comment by jcesarmobile** [comment]
Google don’t want people to convert content urls to file urls for privacy reasons, because content urls don’t belong to your app and they just make it harder on every release.

As workaround you can enable legacy storage, that will work for Android 10, but not for 11 and newer.
For enabling legacy storage add this to the application tag in the `AndroidManifest.xml`

`android:requestLegacyExternalStorage="true"`

or use the dev version of the plugin that enables the legacy storage for you 

https://github.com/apache/cordova-plugin-file/pull/417

**Comment by indraraj26** [comment]
Hi @jcesarmobile,

Thank you for quick reply, If you check above repo you will see i am already using the `android:requestLegacyExternalStorage="true"`

Can you test my repo in your android 10

step to reproduce:

1. open google chrome and search for download dummy pdf and download that file.
2. then open this app and select that downloaded dummy pdf file
