### ISSUE TITLE
File is null on windows

### ISSUE THREAD

**Issue by ravayak** [apache/cordova-plugin-file#445]
File from "@ionic-native/file" on ionic capacitor is null on a windows browser. It's working right on android. 
`
import { File, FileOriginal } from "@ionic-native/file";
`
`
const file: FileOriginal = File;
`
`
console.log(file)
`

![bug report](https://user-images.githubusercontent.com/48095731/101795531-4b0f4080-3b08-11eb-98d2-9319bb50984f.PNG)

### Environment, Platform, Device
A browser on Windows 10 
Ionic version 6.11.9
![package](https://user-images.githubusercontent.com/48095731/101795527-4a76aa00-3b08-11eb-9bf8-75823d4d2666.PNG)

## Checklist
- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
Apache Cordova doesn't maintain `@ionic-native` packages and therefore cannot provide support. You probably want to post your on [Ionic Native's](https://github.com/ionic-team/ionic-native) github repository instead.
