### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by Libelous** [apache/cordova-plugin-file#446]
# Bug Report

## Problem
A typographical error in /www/browser/Preparing.js

occured should be occurred

`  
function (e) {
        console.log('Error occured while trying to request Persistent fs quota: ' + JSON.stringify(e));
    });
`

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks, good catch. I've opened #447 to fix this.
