### ISSUE TITLE
How can i get the real js File Object from the localpath?

### ISSUE THREAD

**Issue by snowdream** [apache/cordova-plugin-file#448]
# Bug Report

### What is expected to happen?
I need the real js File Object, to upload it to the web server.

### What does actually happen?
I get the file from `window.resolveLocalFileSystemURL`，but i find  the file is not the real js File object.

When i upload it to the web server, I find the content of the file is [Object objct].

### Command or Code

```bash
window.resolveLocalFileSystemURL(image.uri, (fileEntry) => {
            console.log(fileEntry)

            fileEntry.file((file) => {

...
```

### Environment, Platform, Device

macbook pro
android emulator
cordova and cordova-plugin-file

**Comment by breautek** [comment]
Unfortunately the `File` type is a special type that cannot be constructed manually, therefore Cordova cannot give you the "real" (browser native `File`) object. Only the browser itself can construct native `File` objects through certain browser APIs.

A workaround is to read the file into a blob, which can be sent to the server in the same way as a `File` type can be. The native `File` type is a `Blob`, so any API that expects a `File` type will also work with a `Blob` type.

see below for an example of how to read the file as a blob:

```js
function readBinaryFile(fileEntry) {

    fileEntry.file(function (file) {
        var reader = new FileReader();

        reader.onloadend = function() {

            console.log("Successful file write: " + this.result);
            displayFileData(fileEntry.fullPath + ": " + this.result);

            var blob = new Blob([new Uint8Array(this.result)], { type: "image/png" });
            displayImage(blob);
        };

        reader.readAsArrayBuffer(file);

    }, onErrorReadFile);
}
```
