### ISSUE TITLE
I can not write image to the ios gallery with 'cordova-plugin-file'

### ISSUE THREAD

**Issue by snowdream** [apache/cordova-plugin-file#451]
# Bug Report

## Problem

I have a image with base64 data.
now  i want to write the image to the ios gallery with 'cordova-plugin-file',But i failed.
I do not know which path i can write to .

cordova.file.dataDirectory?
cordova.file.documentsDirectory?

### What is expected to happen?
The image can be shown in the gallery of the iphone.

### What does actually happen?
The image can not be shown in the gallery of the iphone.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).

**Comment by jfoclpf** [comment]
> You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).

@timbru31 actually it has been asked one year ago, with no conclusive replies
https://stackoverflow.com/questions/60559455/how-to-save-file-in-ios-using-cordova-plugin-file
Could you kindly take a look?

I'm having exactly the same issue. Thanks

**Comment by breautek** [comment]
> I'm having exactly the same issue. Thanks

IOS is a closed system. You can't access the iOS gallery via the filesystem.

There are special native apis for writing and reading to the gallery. You'll need to find a plugin, or write your own that interfaces these APIs.

I'm not an expert on native iOS development but I believe 
https://developer.apple.com/documentation/photokit would be helpful should you write your own plugin.

**Comment by jfoclpf** [comment]
Thank you @breautek indeed it seems another user used `cordova-plugin-x-social-sharing` to save files in iOS accessible to end user. I'll give a try. Do you happen to know any other plugin applicable therefor?

**Comment by breautek** [comment]
> Thank you @breautek indeed it seems another user used `cordova-plugin-x-social-sharing` to save files in iOS accessible to end user. I'll give a try. Do you happen to know any other plugin applicable therefor?

No. That's not a problem I ever needed to solve. Sorry.

**Comment by jfoclpf** [comment]
Thanks anyway. Have a great day

**Comment by jfoclpf** [comment]
Just to let you know that this issue [is fixed](https://stackoverflow.com/a/66553700/1243247). I tested now and it does work!

Simply edit your `config.xml` adding these entries inside `<platform name="ios">`

```xml
<edit-config target="UIFileSharingEnabled" file="*-Info.plist" mode="merge">
  <string>YES</string>
</edit-config>
<edit-config target="LSSupportsOpeningDocumentsInPlace" file="*-Info.plist" mode="merge">
  <string>YES</string>
</edit-config>
<edit-config target="UISupportsDocumentBrowser" file="*-Info.plist" mode="merge">
  <string>YES</string>
</edit-config>
```

I'd say you can close the issue.
