### ISSUE TITLE
this.file.* all keys are null

### ISSUE THREAD

**Issue by mayankkataria** [apache/cordova-plugin-file#452]
I'm using this plugin with ionic capacitor instead of cordova with help of command ```ionic cap sync```. I wanna use ```this.file.externalRootDirectory``` to get root directory from my android device but I'm getting ```null```. Then I wondered if I could try any other option but all options of ```this.file``` were null. I tried to reinstall plugin and rebuild the project but the result is same.
My code: 
```
constructor(private file: File, private plt: Platform) { }
ionViewDidEnter() {
  this.plt.ready().then(() => {
    setTimeout(() => console.log(this.file), 1000); // all values are null
  })
}

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
