### ISSUE TITLE
Cannot build the app with cordova error.

### ISSUE THREAD

**Issue by pattypotpot** [apache/cordova-plugin-file#455]
![image](https://user-images.githubusercontent.com/78461225/106696698-38048280-6618-11eb-9b67-df4d12eda806.png)

**Comment by breautek** [comment]
Version 4.3.3 is old and cannot be supported.

Please try using the current release, version 6.0.2 instead. If you need further assistance, then try reaching out to our community on [slack](http://slack.cordova.io/). If you think you've found a bug, then open a new issue with the issue form **filled out**.
