### ISSUE TITLE
Can't read file outside of app dirs

### ISSUE THREAD

**Issue by LoranRendel** [apache/cordova-plugin-file#456]
# Bug Report

### What is expected to happen?
Successful file read

### What does actually happen?
File error 1

## Information

Debug console content
![изображение](https://user-images.githubusercontent.com/7853801/107155635-8607e600-698a-11eb-9c75-22994ef9e932.png)

### Command or Code

```js
function readFile(fileEntry) {
    fileEntry.file(function (file) {
        console.log(file);
        var reader = new FileReader();

        reader.onloadend = function () {
            console.log("Successful file read: " + this.result);
            console.log(this);
        };

        reader.readAsText(file);

    }, onErrorReadFile);
}

function onErrorReadFile(e) {
    console.log('error: ' + e);
}

window.resolveLocalFileSystemURL(cordova.file.externalRootDirectory + "test.txt",
    readFile,
    function (e) {
        console.log('unable to read', e);
    }
);
```

### Environment, Platform, Device

Android 10

### Version information

Cordova 10.0.0, Android platform 9.0.0, cordova-plugin-file 6.0.2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
This is **suppose** to work on API 29 with the `requestLegacyExternalStorage` enabled (which if you use the dev copy from github master branch, the plugin does use this flag). Can you try the plugin by installing it from git?

```
cordova plugin add https://github.com/apache/cordova-plugin-file.git
```

Please do let me know of this works, I'll be planning on making a release so that people can start making their migrations. Accessing the external storage root will not be possible starting API 30.

**Comment by LoranRendel** [comment]
> 
> 
> This is **suppose** to work on API 29 with the `requestLegacyExternalStorage` enabled (which if you use the dev copy from github master branch, the plugin does use this flag). Can you try the plugin by installing it from git?
> 
> ```
> cordova plugin add https://github.com/apache/cordova-plugin-file.git
> ```
> 
> Please do let me know of this works, I'll be planning on making a release so that people can start making their migrations. Accessing the external storage root will not be possible starting API 30.

Yes, now it works in Android 10 / API 29.

However, will there be a solution to reading files in API 30? If application is designed to work with files it will be useless if there will be no way to access FS.

**Comment by breautek** [comment]
> However, will there be a solution to reading files in API 30? If application is designed to work with files it will be useless if there will be no way to access FS.

Android is going to limit the ability to access the file system outside of your app's sandbox, so accessing these files won't be possible starting API 30 as they once were. Android has a `MediaStore` API that we either need to figure out how to implement within the file plugin or perhaps as an entirely new plugin. The MediaStore is no way alike the the FS API so it may be completely out of scope for this plugin.

With that being said, there will be some external files that will become inaccessible starting API 30 as the MediaStore doesn't provide access to everything. For example, `cordova.file.externalRootDirectory + "test.txt"` will likely become impossible to access using the new APIs which will be enforced starting API 30. Likewise, if you have any custom folders that you used inside the external root directory, they'll become inaccessible. [Google](https://developer.android.com/about/versions/11/privacy/storage) states:

> If your app uses the legacy storage model and previously targeted Android 10 or lower, you might be storing data in a directory that your app cannot access when the scoped storage model is enabled. Before you target Android 11, migrate data to a directory that's compatible with scoped storage.

**Comment by jfoclpf** [comment]
I'd suggest to close this issue because it is a repetition of #426

**Comment by breautek** [comment]
> I'd suggest to close this issue because it is a repetition of #426

Agreed

https://github.com/apache/cordova-plugin-file/issues/426#issuecomment-830841544
