### ISSUE TITLE
readAsDataUrl promise not resolving

### ISSUE THREAD

**Issue by mayankkataria** [apache/cordova-plugin-file#463]
```
this.file.readAsDataURL(this.file.externalCacheDirectory, '1614879497083-cropped.jpg')
      .then(dataUrl => {
        console.log('data url: ', dataUrl);
      })
      .catch(err => console.log('err: ', err));
```
If I change the file name than error code is logged in console but when the file name is correct, NOTHING is logged in console. There's no error in console either which means the plugin has accessed the file successfully but the promise is not getting resolved.

**Comment by breautek** [comment]
Cordova doesn't implement promises in the Filesystem API, so promise issues must be coming whatever framework/library you're using.

Should you determine that the promise is not resolving due to a bug within Cordova's codebase, please do open a new issue with the issue form filled out completely; pointing at the problematic code in Cordova's codebase.

Kind regards,
Norman

**Comment by mayankkataria** [comment]
Well, cordova does implement promises because from the same plugin I've implemented ```writeFile()``` method which is a Promise and was successfully resolved.

**Comment by faugusztin** [comment]
@mayankkataria Promise based interface comes from Ionic wrapper of the cordova-plugin-file (@ionic-native/file/ngx).

There are multiple issues logged with your problem at ionic-native github:
https://github.com/ionic-team/ionic-native/issues/3289
https://github.com/ionic-team/ionic-native/issues/3574

There is also a specific comment which might explain why the Ionic wrapper doesn't work correctly:
https://github.com/ionic-team/ionic-native/issues/3265#issuecomment-735029628

If you need to get it working ASAP, you should ditch the Ionic plugin wrapper for now and use the actual Cordova File plugin API.

**Comment by mayankkataria** [comment]
O sry I got it. Btw I found the workaround with ```Filesystem.readFile()``` in case if it helps someone.
```
import { Plugins } from '@capacitor/core';
const { Filesystem } = Plugins;
...
Filesystem.readFile({
      path: this.file.externalCacheDirectory + '1614879497083-cropped.jpg'
    })
      .then(res => {
        console.log('fs: ', res.data);
      })
      .catch(err => console.log('fs err: ', err));
```

**Comment by Vetusik** [comment]
@mayankkataria 
Thanks a lot! This fixed my issue

**Comment by mraza007** [comment]
@mayankkataria 

Thanks a tonn 


This resolved my issue as well I can't thank enough
