### ISSUE TITLE
Cordova crash building OS X

### ISSUE THREAD

**Issue by jeezs** [apache/cordova-plugin-file#465]
# Bug Report

## Problem
When adding the plugin to the Cordova app, this one can't be compiled anymore
### What is expected to happen?
create an OS X app

### What does actually happen?

unable to build the app :  here is the error : 
/Users/me/Desktop/HelloCordova/platforms/osx/build/HelloCordova.build/Debug/HelloCordova.build/Script-70BD687218FFB1A300A1EFCF.sh: line 2: cordova/lib/copy-www-build-step.sh: No such file or directory

### Command or Code

cd desktop
cordova create HelloCordova
cd HelloCordova
cordova plugin add cordova-plugin-file
cordova platform add osx
cordova run osx

### Environment, Platform, Device

OSx Catalina, big sure

### Version information

XCODE 12.4 on Catalina 10.15.7 ( also try on big sure)
Cordova osx platform version 6
Cordova version 10
Nothing else

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
[Cordova OSX](https://cordova.apache.org/announcements/2022/03/22/osx-deprecation.html) has been deprecated making this issue obsolete.
