### ISSUE TITLE
Code 1 ;File not found error

### ISSUE THREAD

**Issue by harunme3** [apache/cordova-plugin-file#466]
When do I install apk first time copyfile() method working as expected,but while I installed my app second time it give me File not found error

this.file .checkDir(root, 'target')
      .then(() => {
        this.file
          .copyFile(dirctorypath, filename, root+'target', '')
          .then((t) => {
            console.log('saved');
          })
          .catch((err) => {
            console.log(err);
            console.log('File not found');
          });
      })
      .catch((err) => {
        //create nd copy
        this.file
          .createDir(root, 'target', true)
          .then(() => {
            this.file
              .copyFile(dirctorypath, url, root + `'target',` '')
              .then((t) => {
                console.log('saved');
              })
              .catch(() => {
                console.log('not saved');
              });
          })
          .catch(() => {
            console.log(err);
          });
      });

**Comment by Jdonerme** [comment]
you might want to look at this thread: https://github.com/apache/cordova-plugin-file/issues/426

Adding ' android:requestLegacyExternalStorage="true"' to my AndroidManifest.xml solved the problem for me

**Comment by harunme3** [comment]
I already added this android:requestLegacyExternalStorage="true in my config.xml and AndroidManifest.xml.
Everything works fine but problem is when I installed my app second time,It gives me file not found error while copying file one location to other location(App directory).
But when I delete my App directory folder manually It work fine.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
