### ISSUE TITLE
Not able to download File in Android

### ISSUE THREAD

**Issue by phoenix503** [apache/cordova-plugin-file#480]
# Bug Report

### What is expected to happen?
It should download the file as expected

### What does actually happen?
Showing me the error

## Information

        FileTransferError {code: 3, source: "https://www.learningcontainer.com/wp-content/uploa…Image-File-for-Testing.png?ezimgfmt=ng:webp/ngcb4", target: "file:///storage/emulated/0/sample_image.jpg", http_status: 401, body: null, …}
        body: null
        code: 3
        exception: null
        http_status: 401
        source: "https://www.learningcontainer.com/wp-content/uploads/2020/09/Sample-Image-File-for-Testing.png?ezimgfmt=ng:webp/ngcb4"
        target: "file:///storage/emulated/0/sample_image.jpg"
        __proto__: Object

### Command or Code

      this.fileTransfer
          .download("https://www.learningcontainer.com/wp-content/uploads/2020/09/Sample-Image-File-for-Testing.png?ezimgfmt=ng:webp/ngcb4",
            this.file.externalRootDirectory + 'sample_image.jpg'
          )
          .then(
            (data) => {
              console.log(data);
            },
            (err) => {
              console.log(err);
            }
          );

### Environment, Platform, Device

Android API 30

### Version information

Added all the permissions for Storage 
Also

       android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true"
  uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
  uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
  uses-permission android:name="android.permission.INTERNET" 

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by sirineKr** [comment]
Hello,

`android:requestLegacyExternalStorage="true"` works when targeting API 29. This won't work when targeting API 30, as API 30 ignores the `android:requestLegacyExternalStorage` attribute.

According to the [Android documentation](https://developer.android.com/training/data-storage/use-cases#opt-out-in-production-app) : 
_After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices._


You can see this [issue]https://github.com/apache/cordova-plugin-file/issues/426#issuecomment-756757287) for more information

I'm facing the same problem, I want to download files in the Download folder without adding `MANAGE_EXTERNAL_STORAGE` permissions on Android 11.

**Comment by breautek** [comment]
External root directory is no longer a writable path. You must use one of the system provided sub directores (e.g. `Downloads/`, `Pictures/`, etc).

Or better, use internal storage instead if you don't need to "share" the file with other apps.

Closing this as it's something we cannot honour
