### ISSUE TITLE
 The downloaded file is only 0 KB

### ISSUE THREAD

**Issue by biwuyi** [apache/cordova-plugin-file#485]
`$('#saveFile').bind('click', function download() {
		var data = generateCodeFile();
		var blob = new Blob([data], {
		    type: "application/json"
		});
		if (window.cordova && cordova.platformId !== "browser") {
            document.addEventListener("deviceready", function() {
                var folderPath = cordova.file.externalCacheDirectory;
                window.resolveLocalFileSystemURL(
                    folderPath,
                    function(dir) {
                    dir.getFile(
                        "my.cube",
                        {
                        create: true
                        },
                        function (file) {
                            file.createWriter(
                                function (fileWriter) {
                                fileWriter.write(new Blob(['some file data'], { type: 'text/plain' }));

                                fileWriter.onwriteend = function () {
                                    alert(blob)
                                };

                                fileWriter.onerror = function (err) {
                                    alert("Unable to download2");
                                    console.error(err);
                                };
                                },
                                function (err) {
                                // failed
                                alert("Unable to download3");
                                console.error(err);
                                }
                                );
                            },
                            function (err) {
                            alert("Unable to download4");
                            console.error(err);
                            }
                        );
                        },
                    function(err) {
                    alert("Unable to download5");
                    console.error(err);
                    }
                );
            });
        } else {
            saveAs(blob, "my.cube");
        }
	});`
![微信截图_20210715094004](https://user-images.githubusercontent.com/87455764/125714545-6e9e59ad-d53e-41f8-b6ff-ed78e1a515d8.png)

**Comment by breautek** [comment]
The provided code works for me. Please ensure you're using the latest cordova-plugin-file. If the issue persists, please include the entire issue template.
