### ISSUE TITLE
FileError {code: 5, message: "ENCODING_ERR"}

### ISSUE THREAD

**Issue by manel00** [apache/cordova-plugin-file#486]
# Bug Report

Cannot write date and time on the file

## Problem

  var n = "data_"+new Date().toLocaleDateString()+"_"+new Date().toLocaleTimeString()+".csv" it works perfect but gives error on Ionic when you write a file

### What is expected to happen?

To write the file

### What does actually happen?

FileError {code: 5, message: "ENCODING_ERR"}

## Information

    var fileName = "data_"+new Date().toLocaleDateString()+"_"+new Date().toLocaleTimeString()+".csv"

    this.file.writeFile(`${this.file.externalRootDirectory}/Download`, fileName, csv, {
      replace: true
    }).then((res) => {
      console.log(res)
    }).catch((error) => {
      console.log(error)
    });

### Environment, Platform, Device

Ionic 5, Angular 10

## Checklist

- [ X] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by CodeWithOz** [comment]
@manel00 did you find a solution to this?

**Comment by rikutys** [comment]
I had the same issue here, 
I try to change `<preference name="android-targetSdkVersion" value="30" />` to 29 and is working, but I know in google play store target will be 30 start from 1st Dec
I also tried adding preserveLegacyExternalStorage=true in the config.xml but not working also. 
I refer from :
https://stackoverflow.com/questions/63364476/requestlegacyexternalstorage-is-not-working-in-android-11-api-30

**Comment by sajath-45** [comment]
any solution?

**Comment by breautek** [comment]
We can't address ionic/angular issues here.

I'd recommend avoid using special characters in file names or file paths however, which those APIs may return depending on the local phone locale.

If the issue persists in a pure cordova app or is reproducible in a [minimal reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) feel free to create a new issue accordingly.

**Comment by roman-rr** [comment]
This issue fixed for me by adding this line (probably root,assets)

```xml
<preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets,root" />
```
