### ISSUE TITLE
warn: Plugins are missing dependencies

### ISSUE THREAD

**Issue by DDholiyan** [apache/cordova-plugin-file#488]
I just install plugin via android studio.
It gives warning "Plugins are missing dependencies"

[capacitor]        cordova-plugin-file-transfer@1.7.1
[capacitor] [warn] Plugins are missing dependencies.

**Comment by breautek** [comment]
```
norman@norman-P15:/development/cordova/test$ cordova create filedeptest
Creating a new cordova project.
norman@norman-P15:/development/cordova/test$ cd filedeptest/
norman@norman-P15:/development/cordova/test/filedeptest$ cordova plugin add cordova-plugin-file
Adding cordova-plugin-file to package.json
```

cordova-plugin-file installs fine when using cordova cli.
