### ISSUE TITLE
Cannot read or delete files under cordova.file.externalRootDirectory for Android 10

### ISSUE THREAD

**Issue by necrodamus** [apache/cordova-plugin-file#496]
# Bug Report
i Cannot read files under cordova.file.externalRootDirectory for Android 11

## Problem
I can not read or delete files in android 10
cordova.file.externalRootDirectory
'file:///storage/emulated/0/'
### What is expected to happen?
delete file 
### What does actually happen?
Type error 5

![image](https://user-images.githubusercontent.com/26715966/134566274-27574588-7251-4548-bbb8-c82e3d682bed.png)
![image](https://user-images.githubusercontent.com/26715966/134567720-88d036f3-8f6f-4c41-a57a-52d23e14e14a.png)
![image](https://user-images.githubusercontent.com/26715966/134567836-7f1f6bef-d411-4c66-8281-f6e29feceb27.png)
![image](https://user-images.githubusercontent.com/26715966/134567859-bf629542-35c4-46bb-9afd-42c6f0ee10b6.png)

## Information

window.resolveLocalFileSystemURL(
    "file:///storage/emulated/0/Pictures/IMG_20210923_112519.jpeg",
    function(fileEntry) {
      console.log("ENTRY URL " + fileEntry.toURL());
      console.log("IS FILE: " + fileEntry.isFile);
      fileEntry.remove(function (file) {
        
        console.log("file removed!");
    }, function (error) {
        
        console.log("error occurred: " + error.code);
    }, function () {
         $parameters.log = "file does not exist";
        console.log("file does not exist");
    });

      fileEntry.file(function(file){
        console.log("FILE: " + file.name);
        console.log("SIZE: " + file.size);
        console.log("TYPE: " + file.type);
  
        var reader = new FileReader();
        reader.onloadend = function() {
          console.log("READER END");
          console.log(this.result);
        };
        reader.onerror = function(er) {
          console.log("READER ERROR");
          console.log(er);
        };
  
        reader.readAsDataURL(file);
      }, console.error);
    },
    console.error
  );

### Command or Code

window.resolveLocalFileSystemURL("file:///storage/emulated/0/Pictures/IMG_20210923_112519.jpeg", function(f) {
    f.filesystem.root.remove(function(){console.log('ok root')}, function(error){console.log(error)})
  });

### Environment, Platform, Device

I try with this , the same  isue in delete
{
    "plugin": {
        "url": "https://github.com/breautek/cordova-plugin-file.git#feat/api30"
    }
}

## Checklist

- [ x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Can't promise **when**... but I'll try to add this case to my [Test App](https://github.com/breautek/cordova-file-api30-test-app)

**Comment by necrodamus** [comment]
Thanks a lot Breautek i have these permisions to write and read , but is not working, i hope in the future a fix. 
![image](https://user-images.githubusercontent.com/26715966/134569839-c5b06861-5aa3-4947-aeff-afeaae637ff0.png)

**Comment by breautek** [comment]
Google doesn't really provide any concrete details but [they do say](https://developer.android.com/about/versions/11/privacy/storage#permissions-target-11)

> If your app targets Android 11, both the WRITE_EXTERNAL_STORAGE permission and the WRITE_MEDIA_STORAGE privileged permission no longer provide any additional access.

`WRITE_EXTERNAL_STORAGE` is the permission originally required to write to any file in external storage (that is `/sdcard/` for devices with an actual sd card or `/storage/emulated/0/` for devices with emulated external storage, which are most modern devices today). As of API 30, `WRITE_EXTERNAL_STORAGE` does not grant any special behaviours, and is essentially ignored/no-op. In my testing, you can write to certain external file paths, e.g. `Downloads/`, `Media/`, `Pictures/`, etc... but apps can no longer modify files under the external directories unless if the app itself was the creator of the file (at least that's my current interpretation/understanding of the [google android docs](https://developer.android.com/training/data-storage/shared/media#request-permissions)).

If you're using a plugin such as the camera plugin to obtain pictures, it would be important to note that your app **is not** the creator of the image, and instead the Camera app on the device is. Therefore you should have read access with `READ_EXTERNAL_STORAGE` permission granted, but you cannot write or make modifications to the file. You **should** be able to write a copy of that file under a different filename.

**Comment by brunoalex** [comment]
i am trying to acess device galery to select a picture and upload it ...but its not working with sdk30, im geting file:///data/user/0/events.staff.booking.app/cache/myimage.jpg?1637341097796 to upload but it failes...and i cant get acess to the image on that path

**Comment by hardslk** [comment]
Hey,
I am also facing the same issue for android 11.
after giving MANAGE_EXTERNAL_STORAGE its work but my application reject in play store.

so, please help as soon as possible.

**Comment by breautek** [comment]
> he externalRootDirectory directory is no longer a writable path with the Android's new filesystem. Google doesn't explicitly say which paths are no longer accessible, but it does [vaguely](https://developer.android.com/about/versions/11/privacy/storage#migrate-data-for-scoped-storage) say that some paths that used to be writable will no longer be accessible.

>>If your app uses the legacy storage model and previously targeted Android 10 or lower, you might be storing data in a directory that your app cannot access when the [scoped storage](https://developer.android.com/training/data-storage#scoped-storage) model is enabled...

https://github.com/apache/cordova-plugin-file/issues/408#issuecomment-1126059587

For this reason I'm closing this as won't fix.

@hardslk The `MANAGE_EXTERNAL_STORAGE` is kind of an escape-hatch permission that allows full control over the android filesystem. It is available to third-party apps (such as apps developed by us) but you have to justify the reason for using hte permission to Google. Typically this permission is for File manager or virus scanner kind of apps where they require broad unrestricted access as a core functionality of their app.
