### ISSUE TITLE
Unable to read from external storage using 'readAsBinaryString' method in Android 11

### ISSUE THREAD

**Issue by kalandher** [apache/cordova-plugin-file#499]
# Bug Report

Unable to read from external storage(file:///storage/emulated/0/Download/) using 'readAsBinaryString' method

### What is expected to happen?
Should be able to read file and success of  file.readAsBinaryString() method should have binary of selected file. 

### What does actually happen?
Success of  file.readAsBinaryString() is returning null

### Command or Code

```
self.file.readAsBinaryString(path, fileName)
                        .then(function (success) {
                        self._zone.run(function () {
                            self.attachmentFile = {
                                fileName: onlyName,
                                fileExtension: ext,
                                data: btoa(success)
                            };
                        });
                    }).catch(function (error) {
                        console.log("readAsBinaryString fail", error);
                    })
```

### Environment, Platform, Device

Onplus 7 

### Version information

Android version - 11,
sdk - 30
cordova - 10.0.0
ionic - v3
cordova-plugin-file - "6.0.2"

## Checklist

- [x] I searched for existing GitHub issues
- [] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by bhandaribhumin** [comment]
@breautek Thanks, Android-scoped-storage solves multiple problems. We are waiting for a new version like the camerahttps://github.com/apache/cordova-plugin-camera/blob/master/RELEASENOTES.md#600-aug-19-2021

**Comment by gchen888** [comment]
@breautek Will there be any solution for this issue in the plugin in the foreseeable future?
