### ISSUE TITLE
How to access files in android sdk 30

### ISSUE THREAD

**Issue by danicarla** [apache/cordova-plugin-file#502]
HI guys...

I found the archives this way:

_///storage/emulated/0/Android/data/myappid/files/
///storage/emulated/0/Android/data/myappid/cache/_

And now which path should I use?

**Comment by breautek** [comment]
See [Where to Store Files](https://github.com/apache/cordova-plugin-file#where-to-store-files)

Generally speaking, I'd advise against using the `cordova.file.external*` paths (which all translate to `/storage/emulated/0/` on android, unless you have a really good reason to use them. External paths are very restrictive, especially as of API 29.

If you're storing app files, the recommended path would be `cordova.file.dataDirectory`

**Comment by danicarla** [comment]
My application downloads some images and previously i chose the directory that stored these images
Now I'm not specifying a directory, I'm just putting "cordova.file.dataDirectory" and the download is done successfully.

I can even see that the size of the app has increased, but I can't access these images 
Which path should i use to access these images?

In [https://github.com/apache/cordova-plugin-file#where-to-store-files](url) say to use `<img src="file:///android_asset/files/teste.jpg" width="70%">` but dont work

**Comment by clarklight** [comment]
I am also having the same issue with cordova.file.dataDirectory, when i try to use the nativeURL within the fileEntry response, it will give the not allowed to load local resources error.

**Comment by danicarla** [comment]
@clarklight Did you find any solution?

**Comment by clarklight** [comment]
@danicarla take a look at this thread, see if it helps. https://github.com/apache/cordova-plugin-file/issues/509#issuecomment-1047178722

People in that thread seems to have similar issues and found a solution, but i did a work around with turning the image into base64 for display.

**Comment by danicarla** [comment]
@clarklight I don't think I can do that, my app uses more than 20,000 images :(

**Comment by breautek** [comment]
If you're trying to load stored images into dom, then

https://github.com/apache/cordova-plugin-file/pull/517 may help, available in the latest file plugin release.
