### ISSUE TITLE
Not able to record audio in Android 10

### ISSUE THREAD

**Issue by July-** [apache/cordova-plugin-file#503]
The following code works in Android 8:
```
var onSuccess = function (e) {
	console.log('onSuccess', e);
};
var onError = function (e) {
	console.log('onError', e);
};
my_media = new Media(cordova.file.externalDataDirectory + 'audio.mp3', onSuccess, onError);
my_media.startRecord();
```

However startRecord gives an error {code: 1} in Android 10.

What have I tried with same result: 

```
my_media = new Media(cordova.file.cacheDirectory + 'audio.mp3', onSuccess, onError);
my_media.startRecord();

my_media = new Media(cordova.file.applicationStorageDirectory + 'audio.mp3', onSuccess, onError);
my_media.startRecord();

my_media = new Media(cordova.file.dataDirectory + 'audio.mp3', onSuccess, onError);
my_media.startRecord();
```

I also tried to create file before recording:
```
resolveLocalFileSystemURL(cordova.file.externalDataDirectory , function (entry) {
	entry.getFile('audio.mp3', {
		create: true,
		exclusive: false
	}, function (fileEntry) {
		console.log('getFile', fileEntry);
                my_media = new Media(cordova.file.externalDataDirectory + 'audio.mp3', onSuccess, onError);
                my_media.startRecord();
	}, function (err) {
		console.log(err);
	});
	}, function (err) {
	console.log(err);
});
```

The file is created but recording does not start.
Please tell if I am doing something wrong or if this plugin is not working with Android 10+ so I will not waste my days trying to make it work.

P.S. similar issues suggests requestLegacyExternalStorage flag but it is not solving problem anymore because Play Market now requires apps to use API level 30.

**Comment by July-** [comment]
Sorry, posted in wrong repository.
Moved my question to https://github.com/apache/cordova-plugin-media/issues/322

**Comment by ibrahimahmed** [comment]
@July- did you able to solve it facing the same issue for android 10 and 11

**Comment by July-** [comment]
@ibrahimahmed No, waiting for the plugin to update
