### ISSUE TITLE
Writte file to other device via network

### ISSUE THREAD

**Issue by monschine** [apache/cordova-plugin-file#504]
# Feature Request

## Motivation Behind Feature
Stablish a communication with external devices

## Feature Description
I would like to be able to write a file to ricoh theta camera with cordova app, taking into account they are connected via wlan.

"thetaIP" : 'http://192.168.1.1:80',

http://192.168.1.1/files/90014a68423861503e030e32c4d68500/100RICOH/nameOfmyFile.JPG

Thanks in advance

**Comment by breautek** [comment]
Networking is out of scope of this plugin, which is to provide an interface to the local file system mimicking the [W3C File API](https://www.w3.org/TR/FileAPI/) as much as possible.

Additionally, you can already read a file either as text or binary and use the standard browser `XMLHttpRequest` to send files to a remote server. You'd have to conform to the remote servers API (e.g. `http://192.168.1.1:80'` must be programmed to accept files and write to disk).
