### ISSUE TITLE
How to Load Resource File Produced During the Build Phase

### ISSUE THREAD

**Issue by allidoisace** [apache/cordova-plugin-file#506]
I would like to store a Binary file so that when a build creates the iOS app, I am able to access the Binary file in Library or Documents. I can’t find any information on how to achieve this and utilize this plugin to access it.

**Comment by breautek** [comment]
A build cannot store the file in the library or documents. You can bundle resource files, which will live in a read only directory along with your other app files [cordova.file.applicationDirectory](https://github.com/apache/cordova-plugin-file#file-system-layouts) (if I recall properly, it may be in a subdirectory thereof.)

If you want the file to be placed in another location, then you'll need to manually copy the file in the app runtime. The docs with examples of how to read/write files can be found [here](https://github.com/apache/cordova-plugin-file#sample-create-files-and-directories-write-read-and-append-files-).
