### ISSUE TITLE
Cannot read PDF, .Docx from Internal Storage using cordova.file.externalRootDirectory for Android 11

### ISSUE THREAD

**Issue by ragul02** [apache/cordova-plugin-file#508]
# Bug Report

## Problem
Not able to read PDF and .Docx files from location file:///storage/emulated/0/Download/. Also not able to read files recursively inside directories, Returning array length of '0'.

### What is expected to happen?
Should return all files under location file:///storage/emulated/0/Download/

### What does actually happen?
Able to read only  .jpeg, .gif, .mp3, ,mp4 files.

### Command or Code
listFilesinFolder(folderName) {
this.file.listDir(this.file.externalRootDirectory, 'Download'+'/').then((filesList) => {
      console.log('filesList-->', filesList);
      if (filesList.length !== 0) {      
        Promise.all(filesList.map(async (file) => {
          if (file.isDirectory) {
     console.log('Directory', file);
  this.listFilesinFolder(file.fullPath.substring(1));
          } else if (file.isFile === true) {
            console.log('file', file);
}
}
})));
}
### Environment, Platform, Device
Android 11

### Version information
  "@ionic-native/file": "^5.36.0",
 "cordova-plugin-file": "^6.0.2",

Included below in config.xml:
  <preference name="AndroidPersistentFileLocation" value="Internal" />
  <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
            <application android:requestLegacyExternalStorage="true" android:usesCleartextTraffic="true" />
        </edit-config>

**Comment by ragul02** [comment]
Included below in config.xml:
```xml
<preference name="AndroidPersistentFileLocation" value="Internal" />
  <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
            <application android:requestLegacyExternalStorage="true" android:usesCleartextTraffic="true" />
        </edit-config>
```

**Comment by edvenkat** [comment]
@ragul02  - i have tried but not working. any other idea

**Comment by subranil** [comment]
Does anyone have solution for that
