### ISSUE TITLE
origFileReader is undefined, so File API is still overriding by this plugin

### ISSUE THREAD

**Issue by 1aerostorm** [apache/cordova-plugin-file#521]
I will not fill that issue, because Apache willn't fix plugin anyway

I will just post a work-around:
```js
<script>
var FileReader0 = FileReader
</script>
<script src="cordova.js"></script>
```
And it works with Cordova 11. 

https://github.com/apache/cordova-plugin-file/blob/master/www/FileReader.js#L27 it doesn't.

**Comment by breautek** [comment]
duplicate: https://github.com/apache/cordova-plugin-file/issues/521
