### ISSUE TITLE
Permission denied - Android 12 API 32

### ISSUE THREAD

**Issue by Sebartus** [apache/cordova-plugin-file#540]
## Problem

On Android 12 ( SDK 32 ) I'm receiving "Permission denied" error when I try update DFU from:
`file:///storage/emulated/0/Download/test.zip`

The zip file is in Download catalog on phone storage ( not on card ).

In AndroidManifest.xml I add:
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```
and even:
`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`

**Has the path to the file changed in Android 12 ? 
Is my path correct ?**

I will be grateful for any help or suggestions...

### What does actually happen?

Permission denied

### Key plugins
`android@11.0.0`
`cordova-plugin-dfu-update latest version`
`cordova-plugin-bluetoothle latest version`
`cordova-plugin-file latest version`

**Comment by breautek** [comment]
WRITE_EXTERNAL_STORAGE is deprecated and is a no op when targeting API 30 or later. The scoped storage system does not use the write permission anymore and all apps have limited access to write to the external filesystem.

READ_EXTERNAL_STORAGE however is still used that gives the app permission to read files from external storage that other apps may have written to.

The MANAGE_EXTERNAL_STORAGE is a new permission that allows broad filesystem access to the app, but it requires justification to be used. Google will not allow apps to use this permission unless if they can demonstrate an actual need for broad filesystem access.

>Has the path to the file changed in Android 12 ?
Is my path correct ?

You have an absolute path, the path is not guaranteed to exist on all devices, but any device with a simulated external storage (doesn't have a physical  sd card) have the /storage/emulated path. The 0/ is the device user id, which on most devices is simply 0. So your path looks ok.

> when I try update DFU...

If your app didn't write `file:///storage/emulated/0/Download/test.zip`, then you may not have write access to the file. This is a scoped storage mechanism that changed in API 30, the external storage system is severely restricted to increase privacy. If you have to download app data, you may want to consider using internal storage instead, which does not require any special permissions.

**Comment by breautek** [comment]
Stale.
