### ISSUE TITLE
Create file error code 9

### ISSUE THREAD

**Issue by ptorrent** [apache/cordova-plugin-file#541]
Hello there,

### What is expected to happen?

Create a file if not exists... dir.getFIle("test",{"create":true,"exclusive":false}  ) 

### What does actually happen?

```
dir.getFIle("test",{"create":true,"exclusive":false}  ) result on {"code":9} so not created ?
dir.getFIle("test",{}  ) result on {"code":1} ==> normal

```

I don't understand the goal of { create exclsuive...}, why it's not working like nodejs ?

### Version information

Cordova android@10.0.1
cordova-plugin-file 7.0.0 "File"

Android 12 on my device.

**Comment by breautek** [comment]
The following code works for me assuming that my app has ownership of the file (e.g. the file wasn't written by another app)

```javascript
document.addEventListener('deviceready', onDeviceReady, false);

var testFiles = async function() {
    window.resolveLocalFileSystemURL(cordova.file.externalRootDirectory + 'Download', (downloadsDirEntry) => {
        console.log('DOWNLOADS', downloadsDirEntry);
        downloadsDirEntry.getFile('test1.txt', { create: true }, (fileEntry) => {
            fileEntry.createWriter((writer) => {
                writer.onwriteend = () => {
                    console.log('file written');
                };

                writer.onerror = (error) => {
                    console.error('WRITE ERROR', error);
                };

                writer.write(new Blob(['Hello!'], { type: 'text/plain'}));
            });
        }, (error) => {
            console.error('FILE OPEN', error);
        })
    }, (error) => {
        console.error('DIR READ', error);
    });
};

function onDeviceReady() {
    // Cordova is now initialized. Have fun!

    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
    document.getElementById('deviceready').classList.add('ready');

    testFiles();
}
```

The above code writes the file and can be observed by using `adb pull /storage/emulated/0/Download/test1.txt ./` that both the file exists and contains the contents written.

I don't really know what `exclusive` is used for but it doesn't appear to be required.

Tested against target API 32 / API 32 emulator. Can you please compare, or share some code that reproduces the issue?

**Comment by breautek** [comment]
See https://github.com/apache/cordova-plugin-file/issues/527#issuecomment-1402873214
