### ISSUE TITLE
feat(android): Make permission WRITE_EXTERNAL_STORAGE optional

### ISSUE THREAD

**Issue by DavidTalevski** [apache/cordova-plugin-file#543]
# Feature Request

## Motivation Behind Feature
Most applications and plugin functionalities do not require "android.permission.WRITE_EXTERNAL_STORAGE".

## Feature Description
Adding a variable during installation whether or not to include the permission might be the simplest solution. I'm not exactly sure if the cordova xml structure supports something like checking if a preference is equal to a value and then adding a permission or any other tag.
```xml
<!-- Check if external storage permission should be added? -->
<config-file target="AndroidManifest.xml" parent="/*">
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
</config-file>
```

## Alternatives or Workarounds
A workaround for completely removing the permission is mentioned here: #243 
I'm also using a fork in my projects where the permission is removed directly from the plugin.xml.

**Comment by funkenstrahlen** [comment]
This is also required for REQUEST_INSTALL_PACKAGES as an app build from me was just rejected by Google Play Store. The build includes the permission but we do not use it at all.

**Comment by breautek** [comment]
> This is also required for REQUEST_INSTALL_PACKAGES as an app build from me was just rejected by Google Play Store. The build includes the permission but we do not use it at all.

This plugin does not add the `REQUEST_INSTALL_PACKAGES` permission.

**Comment by breautek** [comment]
Also, just confirmed that `WRITE_EXTERNAL_STORAGE` is completely obsolete when targeting API level >= 30

> Note: If your app targets Build.VERSION_CODES.R or higher, this permission has no effect.

https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE

Therefore rather than making the permission optional, we'll probably just remove it altogether.

**Comment by DavidTalevski** [comment]
> Also, just confirmed that `WRITE_EXTERNAL_STORAGE` is completely obsolete when targeting API level >= 30
> 
> > Note: If your app targets Build.VERSION_CODES.R or higher, this permission has no effect.
> 
> https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE
> 
> Therefore rather than making the permission optional, we'll probably just remove it altogether.
> 
> Additionally, the plugin already is set to support only cordova engines android >= 10.0, which is intended to target API 30, so removing the WRITE declaration completely would not be considered a breaking change.

I am currently targeting API level 31 and I am using my [fork](https://github.com/DavidTalevski/cordova-plugin-file) where I have removed the permission tag from the plugin.xml. I can confirm that there are no issues so far while using the plugin without the permission, as its use was very specific either way (with sd cards only?).

Can we expect the permission to be removed in the next release of this plugin?

**Comment by breautek** [comment]
> Can we expect the permission to be removed in the next release of this plugin?

Yes, but I cannot provide a timeline of when that will be.
