### ISSUE TITLE
entry.toUrl() gives me wrong path in ionic 6 android 12

### ISSUE THREAD

**Issue by swadeshRanjeet** [apache/cordova-plugin-file#551]
main.5dfa0d5a5181c0bf.js:1 ERROR Error: Uncaught (in promise): File Transfer Error: {"code":1,"source":"https://paragmedical.com/style/CompanyList_All.pdf","target":"http://localhost/__cdvfile_sdcard__/Download/2022-12-27T10-24-17-968Z-company.pdf","http_status":200,"body":null,"exception":"URI not supported by Cordova Resource Api: http://localhost/__cdvfile_sdcard__/Download/2022-12-27T10-24-17-968Z-company.pdf"}

see my target url getting wrong =**"http://localhost/__cdvfile_sdcard__/Download/2022-12-27T10-24-17-968Z-company.pdf"**

**Comment by breautek** [comment]
`"http://localhost/__cdvfile_sdcard__/Download/2022-12-27T10-24-17-968Z-company.pdf"` is the expected URL format returned from `toURL` if you have schemes enabled.

It provides a DOM-usable URL that can be used by the standard webview APIs, replacing the old `cdvfile` scheme it used to return, which was not compatible with the `WebViewAssetLoader` system.

The FileTransfer plugin however isn't updated to accept this new URL format. The FileTransfer is not part of the webview and therefore doesn't use the `WebViewAssetLoader` path resolution. Using `.nativeURL` property should be a workaround as it will contain a native `file:` path that it will understand.

We have a ticket inside the file transfer plugin tracking the discussion around support for webviewassetloader URLs: https://github.com/apache/cordova-plugin-file-transfer/issues/339
