### ISSUE TITLE
Cordova can't read files with FileRead

### ISSUE THREAD

**Issue by El-Tommy** [apache/cordova-plugin-file#565]
I'm using JavaScript's FileReader API to try to get the blob of a file inside a Cordova application.

My code is like the example below:

```javascript
originalLocation = 'content://com.android.externalstorage.documents/document/primary%3ADownload%2F1671641692909.jpg';

window.FilePath.resolveNativePath(originalLocation, function (newFilepath) { resolveFilePath(newFilepath) });

function resolveFilePath(location) {
    window.resolveLocalFileSystemURL(location, function (fileEntry) {

        fileEntry.file(function (file) {

            let reader = new FileReader();

            reader.onload = function (event) {
                console.log(reader.result);
                console.log(event);
            }
            reader.onloadstart = function (event) {
                console.log(reader.result);
                console.log(event);
            }
            reader.onloadend = function (event) {
                console.log(reader.result);
                console.log(event);
            }
            reader.onprogress = function (event) {
                console.log(reader.result);
                console.log(event);
            }
            reader.onerror = function (event) {
                console.log(reader.result);
                console.log(event);
                const error = reader.error;
                console.log(error);
            }
            reader.onabort = function (event) {
                console.log(reader.result);
                console.log(event);
            }
            console.log(file);
            reader.readAsArrayBuffer(file);
        });
    });
}
```

```xml
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
       <application requestLegacyExternalStorage="true" />
</edit-config>

<preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets,root" />
<preference name="AndroidPersistentFileLocation" value="Internal" />
<preference name="AndroidPersistentFileLocation" value="Compatibility" />
```

When reading an image, the API works correctly, obtaining the content, but with files that are not images, the FileReader's onerror event always returns the message "FileError {code: 1}". I already tried to read using all possible ways (readAsArrayBuffer, readAsBinaryString, readAsDataURL,readAsText).

The location of files on the smartphone.

- Image before resolveLocalFileSystemURL: `content://com.android.externalstorage.documents/document/primary%3ADownload%2F1671641692909.jpg`
- Image after resolveLocalFileSystemURL: `file:///storage/emulated/0/Download/1671641692909.jpg - Success`
- File before resolveLocalFileSystemURL: `content://com.android.externalstorage.documents/document/primary%3ADownload%2FExample.pptx`
- File after resolveLocalFileSystemURL: `file:///storage/emulated/0/Download/Example.pptx - Error`

What could possibly be happening?

### Environment, Platform, Device
Android 12 - Samsung A 53

### Version information
Cordova: 11.1.0
Cordova-Android:  10.1.2

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
> "FileError {code: 1}". 

This is the error code for file not found, which may be returned by the underlying filesystem API even if the file exists but your app doesn't have permission to read it.

Some files that are in external storage are not readable via filesystem APIs as of API 29. Also note that is obsolete (and ignored) when targeting API 30 or later as the scoped storage rules are enforced. Scoped storage in API 29 devices specifically had no filesystem API, thus it is impossible to read external storage files using this plugin.

Files that are not owned by your application usually needs to go through SAF (Storage Access Framework), which is a non-filesystem like API so it's not implemented as part of this plugin.

Generally speaking this plugin works best for internal storage, or external storage operations where you only read/write files that you control.

I don't use external storage in my apps so I don't have extensive experience, but if you need to access files that aren't owned by your application, then I'd try giving SAF plugin a try, such as [cordova-plugin-saf-mediastore](https://www.npmjs.com/package/cordova-plugin-saf-mediastore) (not an endorsement, just picked a random one from NPM search)

**Comment by El-Tommy** [comment]
The files I'm trying to open are on the device itself and not on external storage.
These files were downloaded via browser.

The strange thing is that only images are successfully read, any other file in the same folder as the images generates the error.

And all files are in `content://com.android.externalstorage.documents/document/primary:Download/`

I don't know if it could be the filepicker I use to choose the files that generates a wrong address.

I still use this one though:

https://www.npmjs.com/package/cordova-plugin-filechooser

**Comment by breautek** [comment]
> The files I'm trying to open are on the device itself and not on external storage.

Android has 2 storage mediums, internal and external storage. Both can be on the device. External storage are generally attached to an SD card (will have a `/sdcard/...` path, however most devices will also emulate external storage if the sdcard is not present, or not supported (generally uses a `/storage/emulated/0/...` path).

So a filepath like `file:///storage/emulated/0/Download/1671641692909.jpg` tells me that you're working with external storage, and thus [Scoped Storage](https://source.android.com/docs/core/storage/scoped) rules applies.

Documents have stricter rules than media files, so if the app has `READ_EXTERNAL_STORAGE` permission granted (and this plugin will request it when appropriate), you may read media off the external storage (subject to permissions set my the app who wrote that media file). However, I don't `READ_EXTERNAL_STORAGE` applies to document files, such as those that are generally found in `Downloads/` or otherwise. I believe the only way to read document files is via the native MediaStore APIs which the file plugin does not implement (they aren't really friendly to file-like API cause they don't really share the same concepts). This is also kinda further enforced that in API 33 and later `READ_EXTERNAL_STORAGE` becomes obsolete in favour of 3 new permissions, `READ_MEDIA_IMAGES`, `READ_MEDIA_AUDIO`, READ_MEDIA_VIDEO`, however there is no explicit `READ` permission for documents.

This is why I suggested something like https://www.npmjs.com/package/cordova-plugin-saf-mediastore which contains APIs like `readFile(uri:string):Promise<ArrayBuffer>`, so the plugin not only provides the way to choose files via MediaStore & the file picker, but to also read and get the contents of the files, or write/overwrite... whereas https://www.npmjs.com/package/cordova-plugin-filechooser looks like only allows you to select files and returns a `content` URL, which thie cordova-plugin-file can only use if it leads to a file that is readable using filesystem APIs.

**Comment by El-Tommy** [comment]
Thanks @breautek ,
The use of this plugin allowed reading the ArrayBuffer of the file in question.

**Comment by oudoken** [comment]
Hi there,
This post has lot of usefull informations.

Just wanting to add a bunch of infos:

- https://github.com/customautosys/cordova-plugin-saf-mediastore work as expected (see later for details on various SDK version specs, the only thing in my configuration (cordova android@12) was to add `implementation` `"androidx.documentfile:documentfile:1.0.1"` to "build.gradle (:app)" on "dependencies {" section

- SAF Mediastore it's made to work as "standalone": You need to use a file picker or another user initiated action for obtaining an content URI wich contain the correct authorization (read/write etc). This mean that You can use this plugin in combination with a "sharing" intent, if Your app it's configured for opening a specific file type this works pretty well thus on SDK 33 You will need to use SAF Mediastore as well for getting the content URI

Tested on these SDK's on emulators and real devices (targetSdkVersion 33):

SDK V 24 - 28 (Android 7.0-9.0): use standard cordova-plugin-file as usual the plugin SAF Mediastore does not work correctly
SDK V 29 - 32 (Android 10.0-12.0): use SAF Mediastore only or mixed SAF Mediastore (to get the arraybuffer) and then use cordova-plugin-file to write the blob from file
SDK V 33 (Android 13.0): use only SAF Mediastore

In AndroidManifest.xml i've modified a little reading and writing permissions:
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32" />


Thanks!
Rob

**Comment by MauriceFrank** [comment]
How could I get the correct content-URI for "ile:///storage/emulated/0/Pictures/cpcp_capture_65e7de6f.jpg"?
I installed the saf-medidastore plugin but I still dont get it to work yet.

I appreciate any help, thank youu!

**Comment by MauriceFrank** [comment]
> Hi there, This post has lot of usefull informations.
> 
> Just wanting to add a bunch of infos:
> 
> * https://github.com/customautosys/cordova-plugin-saf-mediastore work as expected (see later for details on various SDK version specs, the only thing in my configuration (cordova android@12) was to add `implementation` `"androidx.documentfile:documentfile:1.0.1"` to "build.gradle (:app)" on "dependencies {" section
> * SAF Mediastore it's made to work as "standalone": You need to use a file picker or another user initiated action for obtaining an content URI wich contain the correct authorization (read/write etc). This mean that You can use this plugin in combination with a "sharing" intent, if Your app it's configured for opening a specific file type this works pretty well thus on SDK 33 You will need to use SAF Mediastore as well for getting the content URI
> 
> Tested on these SDK's on emulators and real devices (targetSdkVersion 33):
> 
> SDK V 24 - 28 (Android 7.0-9.0): use standard cordova-plugin-file as usual the plugin SAF Mediastore does not work correctly SDK V 29 - 32 (Android 10.0-12.0): use SAF Mediastore only or mixed SAF Mediastore (to get the arraybuffer) and then use cordova-plugin-file to write the blob from file SDK V 33 (Android 13.0): use only SAF Mediastore
> 
> In AndroidManifest.xml i've modified a little reading and writing permissions:
> 
> Thanks! Rob

How did you get the saf-mediastore plugi nto work? 
I struggle getting the right folder path to use for "getUri". I only have a file-URI: "file:///storage/emulated/0/Pictures/cpcp_capture_65e7de6f.jpg". This is basically the Pictures folder but I have no clue how to get thsis path to work with the plugin

**Comment by HackingMinion** [comment]
@MauriceFrank use the `readFile` function

**Comment by craigmuirhead** [comment]
var arrayBuffer = await cordova.plugins.safMediastore
  .readFile(contentUri)
  
  **// find a function to convert to base64 online**
var base64Result = _arrayBufferToBase64(arrayBuffer);

var uploadFileName = await cordova.plugins.safMediastore.getFileName(contentUri)

 var params = new Object();
params.data = base64Result;
params.filename = fullFileName;

var contentUri = await cordova.plugins.safMediastore
  .writeFile(params)

**Comment by alaaahmedmu** [comment]
> 

How to use both standard cordova-plugin-file and SAF Mediastore together.
I mean how to make cordova-plugin-file work with SDK 24 to 28 and Mediastore work with SDK 29 and later, both in the same app?

**Comment by breautek** [comment]
> > 
> 
> @oudoken How to use both standard cordova-plugin-file and SAF Mediastore together. I mean how to make cordova-plugin-file work with SDK 24 to 28 and Mediastore work with SDK 29 and later, both in the same app?

The native `Mediastore` API has been a concept since API 1, while specific features might require higher API levels, the general API should be usable across all API devices. MediaStore was always the recommended/preferred approach over direct filesystem access, it's just being enforced now since API 29 (generally speaking).

You could do version tests (should be able to get the API/android version from the `cordova-plugin-device`) and conditionally use the file plugin on API 24-28, and SAF plugin on API 29+ but personally I'd simplify the logic and use SAF plugin across all android versions, not just for API 29+.

**Comment by etcho** [comment]
@El-Tommy ,
Sorry to post this here, but I'm kinda lost since there are no examples or further documentation about cordova-plugin-saf-mediastore on its repository. I have the same target as you, to read the content of a file chosen by the user and the file plugin stopped working on cordova 12.

I got to prompt the file chooser with it and get the file's URI, but the readFile function just throws an "Uncaught" on the console without any information.

Could you share your example of how to use this function?

**Comment by El-Tommy** [comment]
@etcho,
pt-BR: Eu vou postar todo o meu código desde a parte que o app dispara a escolha de arquivos. Dependendo do local ou gerenciador de arquivos usados no Android, ele pode apresentar problema. É uma confusão.

en-US: _I'm going to post all my code from the part where the app triggers the choice of files. Depending on the location or file manager used on Android, it may have problems. It's a mess._


```
fileChooser.open($scope.selectFileAndUpload, error);

$scope.selectFileAndUpload = function (data) {
    var location;

    if (data.url === undefined) {
        location = data;
    } else {
        location = data.url;
    }

    if (location.indexOf('content://') === 0) {

        window.FilePath.resolveNativePath(location, function (newFilepath) {
            resolveFilePath(newFilepath);
        }, function (error) {
            if (error.code === 0) {
                console.log('Não foi possível ler este arquivo.')
            } else if (error.code === 1) {
                console.log('Problema no Google Drive.',) 
            }
        });
    } else {
        resolveFilePath(location);
    }

}

function resolveFilePath(location) {
    window.resolveLocalFileSystemURL(location, function (fileEntry) {

        fileEntry.file(function (file) {

            let fileType = file.type;

            let reader = new FileReader();

            reader.onloadend = function (e) {
                let imgBlob = new Blob([this.result], { fileType });

                $scope.filesToUpload.forEach(element => {
                    if (element.url === location) {
                        element.blob = imgBlob;
                    }
                });

            }

        }, function () {
            console.log('Ocorreu um erro ao ler o arquivo.');
        });
    }, function (e) {
        console.log('Ocorreu um erro ao ler o arquivo.');
    });
}
```

**Comment by etcho** [comment]
@El-Tommy,

You just saved my life. I had to install `cordova-plugin-filepath`. Maybe all I needed was this, I'm not sure. Now with this plugin installed and adapting your code, the permission to access the file system is prompted before the file reading, which my previous code didn't do.

Thank you very much.
PS: se vc for BR, vlw mais ainda.

**Comment by El-Tommy** [comment]
@etcho
You are welcome.
Because of this, we ended up changing the apps language to Flutter. Lots of headaches with Cordova.

Ps.: Sim, totalmente BR.

**Comment by ferdianarief** [comment]
when i use cordova-plugin-saf-mediastore, i got new issue..

![Screen Shot 2024-05-02 at 22 17 21](https://github.com/apache/cordova-plugin-file/assets/168358294/31f97fb6-9017-4b09-b818-f8a601c4b6e8)

and this is my code :
function getDocValue()
{
	window.fileChooser.open(contentURI => {
	  console.log(JSON.stringify(contentURI));
	
	  var uriParams = {
        folder: 'Documents',
        filename: 'example.pdf'
    };
	  cordova.plugins.safMediastore.getUri(uriParams).then(function(uri) {
		if (uri) {
			console.log('File URI:', uri);

			// Example parameters for writeFile function
			var writeParams = {
				uri: uri,
				content: 'Hello, world!'
			};
		}
	})
	});
}
