### ISSUE TITLE
Plugin doesn't support this project's cordova-android version. cordova-android: 10.1.2, failed version requirement: >=12.0.0 Skipping 'cordova-plugin-file' for android

### ISSUE THREAD

**Issue by richard2189** [apache/cordova-plugin-file#591]
# Bug Report

## Problem
Trying to install this plugin because it is required for cordova-plugin-advanced-http to work
### What is expected to happen?
Run cordova plugin add cordova-plugin-file and it installs

### What does actually happen?
I get:

Plugin doesn't support this project's cordova-android version. cordova-android: 10.1.2, failed version requirement: >=12.0.0
Skipping 'cordova-plugin-file' for android

## Information
I do believe android10.1.2 is the highest level currently on cordova

### Command or Code

cordova plugin add cordova-plugin-file

### Environment, Platform, Device

I am running
Windows 11
Cordova 11.1.0
Android Version 10.1.2

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by XI3310-Abhishek-Dana** [comment]
939364970325
