### ISSUE TITLE
I got a "not a function" error after upgrading to ver 8.0.0.

### ISSUE THREAD

**Issue by tanukki2929** [apache/cordova-plugin-file#595]
I got the following error after upgrading to ver 8.0.0.

> ERROR TypeError: window.resolveLocalFileSystemURL is not a function

Previously, the following were used
https://github.com/MauriceFrank/cordova-plugin-file

I have not changed the process, just increased the version of the plugin, but I wonder what the cause is.

I would be grateful if you could enlighten me.

**Comment by breautek** [comment]
`resolveLocalFileSystemURL` still exists in the official Apache file plugin. We can't really comment on any file plugin forks.
