### ISSUE TITLE
iOS - Privacy Manifest

### ISSUE THREAD

**Issue by amcalgates** [apache/cordova-plugin-file#620]
# Feature Request

## Motivation Behind Feature
On May 1st, Apple will require privacy manifests in all new app store submissions ([source](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc)).

## Feature Description
It appears Cordova has not yet officially added a way for plugins to handle this ([source](https://github.com/apache/cordova-ios/issues/1391)), but the latest cordova-ios release does provide support for an app-level privacy manifest ([source](https://cordova.apache.org/announcements/2024/04/03/cordova-ios-7.1.0.html)).

For the time being, it would be helpful if this plugin could provide a privacy manifest file that consumers could manually cobble together for now, adding full support in the future when Cordova provides a way to do so.

Presumably the only thing we really need from plugins is API usage.

## Alternatives or Workarounds

I can reasonably determine what needs to be included in the privacy manifest so that others can follow suit and manually add these entries to their manifest.

Grepping the plugin's iOS source files

`grep -r -E 'NSURLVolumeAvailableCapacityKey|NSURLVolumeAvailableCapacityForImportantUsageKey|NSURLVolumeAvailableCapacityForOpportunisticUsageKey|NSURLVolumeTotalCapacityKey|NSFileSystemFreeSize|NSFileSystemSize|statfs|statvfs|fstatfs|fstatvfs|getattrlist|fgetattrlist|getattrlistat|activeInputModes|NSUserDefaults'`

Yields:

```
./CDVFile.m:    NSNumber* pNumAvail = (NSNumber*)[pDict objectForKey:NSFileSystemFreeSize];
```

Which is found in the `checkFreeDiskSpace` method.

The usage would seem to possibly fall under two categories:

```
E174.1

    Declare this reason to check whether there is sufficient disk space to write files, or to check whether the disk space is low so that the app can delete files when the disk space is low. The app must behave differently based on disk space in a way that is observable to users.

    Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception that allows the app to avoid downloading files from a server when disk space is insufficient.
```

```
85F4.1

    Declare this reason to display disk space information to the person using the device. Disk space may be displayed in units of information (such as bytes) or units of time combined with a media type (such as minutes of HD video).

    Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception that allows the app to send disk space information over the local network to another device operated by the same person only for the purpose of displaying disk space information on that device; this exception only applies if the user has provided explicit permission to send disk space information, and the information may not be sent over the Internet.
```

If I had to guess, this plugin would probably only  need to cite `E174.1`, but anyone using this plugin on iOS would need to take care when calling `getFreeDiskSpace`, which may warrant a warning in README.md.

**Comment by sc0ttdav3y** [comment]
Thank you for your ongoing work with Cordova @erisu 🥇
